### DISCUSSION TITLE
How to use a custom domain on AKS for deploykf V0.1.4

### DISCUSSION THREAD

**Discussion by gaddamkeerthi** [deployKF/deployKF#112] [Questions & Answers] [answered]
We are using AKS , trying to install deploykf  through argocd  plugin mode .we tried changing the default host to our custom domain hostname url  in the apps_of_apps file and also placed the configurations for exposing the istio gateway service through nginx ingress , followed below document and provided required details 
https://www.deploykf.org/guides/platform/deploykf-gateway/#2-expose-the-gateway-service

Then created the Application , app_of_apps and performed a sync of apps from argocd  UI, All the applications looks healthy and synced status ,But when we hit the url from the deploykf-istio-gateway apps ,it gets redirected to below url (for security reasons the custom url and some encrypted values  has been replaced with *****)

`https://*******.******.******.com:8443/dex/auth?approval_prompt=force&client_id=oauth2-proxy&code_challenge=********encryptedcode*********code_challenge_method=S256&nonce******encryptedcode***********redirect_uri=https%3A%2F%2F*****.*****.******.com%3A8443%2Foauth2%2Fcallback&response_type=code&scope=openid+email+groups+profile+offline_access&state=*********encryptedcode***********siro%3A%2F`

Later its times out , with This site can’t be reached.
We also had added the dex connector configurations for microsoft ( with a clientid and secret ) for the application manifest .But got the same response .
Is there anything else to be done , Will be great help if we get some support or guidance on how to proceed and get the deploykf dashboard accessible through the custom DNS hostname

**Comment by thesuperzapper** [comment, marked as answer]
@gaddamkeerthi some questions:

1. Can you share your `Ingress` YAML?
2. Can you please check the status/logs of the `dex-xxxx` Pods in the `deploykf-auth` namespace?
3. Does the `https://*******.******.******.com:8443/dex/auth...` page actually load, or does it show a blank screen?

**Reply by gaddamkeerthi** [reply]
[deploykf_logs.docx](https://github.com/deployKF/deployKF/files/14443809/deploykf_logs.docx)
I have uploaded a file , which has the ingress object yaml file , dex pod status , logs , app-of-apps manifest changes , argocd  screenshot .
When hit the url the page shows a blank screen

**Reply by thesuperzapper** [reply]
@gaddamkeerthi can you please try a slightly updated Ingress spec (the old one [on the website](https://www.deploykf.org/guides/platform/deploykf-gateway/#expose-with-kubernetes-ingress) had a typo):

__NOTE:__ the difference is in the `path: "/"` and `pathType: Prefix` part

```yaml
deploykf_core:
  deploykf_istio_gateway:

    ## this value adds arbitrary manifests to the generated output
    ##
    extraManifests:
      - |
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: deploykf-gateway
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: HTTPS

            ## nginx wil NOT proxy the SNI by default
            ## see: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#backend-certificate-authentication
            nginx.ingress.kubernetes.io/proxy-ssl-name: "deploykf.example.com"
            nginx.ingress.kubernetes.io/proxy-ssl-server-name: "on"

            ## this config is needed due to a bug in ingress-nginx
            ## see: https://github.com/kubernetes/ingress-nginx/issues/6728
            nginx.ingress.kubernetes.io/proxy-ssl-secret: "deploykf-istio-gateway/deploykf-istio-gateway-cert"
        spec:
          ingressClassName: nginx
          tls:
            ## NOTE: this secret is created as part of the deployKF installation
            - secretName: "deploykf-istio-gateway-cert"
          rules:
            - host: "deploykf.example.com"
              http:
                paths:
                  - path: "/"
                    pathType: Prefix
                    backend:
                      service:
                        name: "deploykf-gateway"
                        port:
                          name: https
            - host: "*.deploykf.example.com"
              http:
                paths:
                  - path: "/"
                    pathType: Prefix
                    backend:
                      service:
                        name: "deploykf-gateway"
                        port:
                          name: https

    ## these values configure the deployKF Gateway Service
    ##
    gatewayService:
      name: "deploykf-gateway"
      type: "ClusterIP"
      annotations: {}
```

**Reply by thesuperzapper** [reply]
@gaddamkeerthi Also, for Ingress, I would not expect to see port `8443` /`8080`. I think that you are accidentally not overriding the default `deploykf_core.deploykf_istio_gateway.gateway.ports` from `sample-values.yaml` (which are set to `8080`/`8443`).

Make sure you include the following values somewhere after the `sample-values.yaml`:

```yaml
deploykf_core:
  deploykf_istio_gateway:
    gateway:
      ports:
        http: 80
        https: 443
```

**Reply by thesuperzapper** [reply]
After looking at your values more closely, I see that you have put `ports` directly under `deploykf_core.deploykf_istio_gateway`, when it needs to be under `deploykf_core.deploykf_istio_gateway.gateway`.

Indent it up by one and your issue should be fixed (but also update the Ingress like I said above).

**Reply by gaddamkeerthi** [reply]
<img width="569" alt="image" src="https://github.com/deployKF/deployKF/assets/105637273/90fe7622-a19b-4f61-9c9b-161fbc991a98">
@thesuperzapper  I have made the changes as suggested but still I dont see the deploykf login page , its a blank page .Is there any else I am missing .Kindly help me understand how do i get the deploykf login page 
Taken care of :
path: "/" and pathType: Prefix
Ports under deploykf_core.deploykf_istio_gateway.gateway

Should I not be using ports 80/443 ? what ports should i need to give under the deploykf_istio_gateway  session? 

Also one QQ , can we install deploykf using flux CD ?

**Reply by thesuperzapper** [reply]
@gaddamkeerthi When using an  Nginx Ingress, you must use `80/443` (its just a requirement of that Ingress controller).

Make very sure your values are indented correctly, the `deploykf_istio_gateway` section is NOT at the root, it's under `deploykf_core`, so your values should look something like this:

```yaml
deploykf_core:
  deploykf_istio_gateway:

    ## this value adds arbitrary manifests to the generated output
    ##
    extraManifests:
      - |
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: deploykf-gateway
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: HTTPS

            ## nginx wil NOT proxy the SNI by default
            ## see: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#backend-certificate-authentication
            nginx.ingress.kubernetes.io/proxy-ssl-name: "deploykf.example.com"
            nginx.ingress.kubernetes.io/proxy-ssl-server-name: "on"

            ## this config is needed due to a bug in ingress-nginx
            ## see: https://github.com/kubernetes/ingress-nginx/issues/6728
            nginx.ingress.kubernetes.io/proxy-ssl-secret: "deploykf-istio-gateway/deploykf-istio-gateway-cert"
        spec:
          ingressClassName: nginx
          tls:
            ## NOTE: this secret is created as part of the deployKF installation
            - secretName: "deploykf-istio-gateway-cert"
          rules:
            - host: "deploykf.example.com"
              http:
                paths:
                  - path: "/"
                    pathType: Prefix
                    backend:
                      service:
                        name: "deploykf-gateway"
                        port:
                          name: https
            - host: "*.deploykf.example.com"
              http:
                paths:
                  - path: "/"
                    pathType: Prefix
                    backend:
                      service:
                        name: "deploykf-gateway"
                        port:
                          name: https

    ## these values configure the deployKF Istio Gateway
    ##
    gateway:
      ## when using an ingress, standard ports are required
      ## (the default in 'sample-values.yaml' are 8080/8443)
      ports:
        http: 80
        https: 443

    ## these values configure the deployKF Gateway Service
    ##
    gatewayService:
      name: "deploykf-gateway"
      type: "ClusterIP"
      annotations: {}
```

Also, regarding FluxCD, right now you [must use ArgoCD](https://www.deploykf.org/guides/dependencies/argocd/#can-i-use-other-tool-instead-of-argo-cd)
Is there a specific reason you want to use FluxCD?

**Reply by gaddamkeerthi** [reply]
@thesuperzapper ,I Have tried the same apps of apps file which you have provided , but still not able to get the url respose with custom url .Is there anything else we can try . This is kind of blocking us from implementing deploykf in our production environment as we dont want to use the default url for accessing the dashboard .

<img width="600" alt="aidev_istio" src="https://github.com/deployKF/deployKF/assets/105637273/0d55e206-7338-4952-aa0b-6ecd98aed8be">
<img width="334" alt="aidev_istio_2" src="https://github.com/deployKF/deployKF/assets/105637273/e5b511cd-1cba-4670-b472-b988b9c79800">

**Reply by thesuperzapper** [reply]
@gaddamkeerthi are those images 100% of your values. That is, are you setting literally any other values in the app-of-apps `values` or `values_files` parameters? If there are any others please list them. Also, can you confirm if you are using the `sample-values.yaml`?

Also, it looks like you are not setting the hostname (at least in the values you showed), make sure you set it to your domain:

```yaml
deploykf_core:
  deploykf_istio_gateway:
    gateway:
      ## the "base domain" for deployKF
      ##  - this domain and its subdomains should be dedicated to deployKF
      ##
      hostname: deploykf.example.com
```

**Reply by thesuperzapper** [reply]
@gaddamkeerthi Also, if you're still having issues after that please just message me on the slack, we might need to do a call to debug.

https://www.deploykf.org/about/community/#slack

**Reply by gaddamkeerthi** [reply]
@thesuperzapper  I am using attached app-of-apps file , where initially ./sample-values.yaml is mentioned at line no 39. Later at line number 45 , the values string is being used to replace the default values, this is where i have mentioned the custom hostname and ingress configuration values.

Then applying this file in argocd namespace , accessing the argocd  UI (used port forwarding ) and running sync of apps is what I have tried so far .When i checked in the parameters tab( on argocd  ui page ) for both app-of-apps and istio-deploykf-istio-gateway , i see ./sample-values.yaml . 

Is this something not correct way to do .If we are unable to trace the issue ,I kindly  request for a call at your availability .
[app-of-apps_current.zip](https://github.com/deployKF/deployKF/files/14691288/app-of-apps_current.zip)

**Reply by thesuperzapper** [reply]
@gaddamkeerthi just do what I said in https://github.com/orgs/deployKF/discussions/112#discussioncomment-8849886.

Your app of apps is missing the `deploykf_core.deploykf_istio_gateway.gateway.hostname` value, so it will be defaulting to `deploykf.example.com`.

You MUST set the following values:

```yaml
deploykf_core:

  deploykf_istio_gateway:

    gateway:

      ## \/\/\/\/\/ THIS ONE \/\/\/\/\/
      hostname: "aidev.maestro.******.com"
```
