### DISCUSSION TITLE
Trying to deploy deployKF to an existing ArgoCD on bare metal cluster with Longhorn storage

### DISCUSSION THREAD

**Discussion by theNewFlesh** [deployKF/deployKF#22] [Questions & Answers]
I am hoping to switch from a Juju Kubeflow deployment to deployKF. I am running my own baremetal cluster with Longhorn installed. I cannot for the life of me figure out how to deploy deployKF such that it uses Longhorn StorageClass for the volumes.

A little help would be great.  Thanks.

**Comment by theNewFlesh** [comment]
Here is the ansible playbook I am attempting to run:

```
- hosts: localhost
  tasks:
    - name: Set deploykf_uri fact
      set_fact:
        deploykf_uri: https://raw.githubusercontent.com/deployKF/deployKF/main/argocd-plugin/argocd-install/deploykf-plugin/

    - name: Set deploykf facts
      set_fact:
        deploykf_plugin_original: "{{ lookup('ansible.builtin.url', deploykf_uri + 'plugin.yaml', split_lines=False) }}"
        deploykf_server_patch: "{{ lookup('ansible.builtin.url', deploykf_uri + 'repo-server-patch.yaml', split_lines=False) }}"
        plugin_patch: |-
          init:
              env:
                - name: PARAM_VALUES
                  value: |
                    deploykf_opt.deploykf_minio.persistence.storageClass: longhorn
                    deploykf_opt.deploykf_mysql.persistence.storageClass: longhorn

    - name: Cleanup deploykf_plugin
      set_fact:
        deploykf_plugin: "{{ deploykf_plugin_original | regex_replace('init:', plugin_patch) }}"

    - name: Create DeployKF PersistentVolume
      k8s:
        state: present
        definition:
          kind: PersistentVolume
          apiVersion: v1
          metadata:
            name: argocd-deploykf-pv
            namespace: argocd
          spec:
            storageClassName: longhorn
            persistentVolumeReclaimPolicy: Retain
            volumeMode: Filesystem
            capacity:
              storage: 1Gi
            accessModes:
              - ReadWriteOnce
            csi:
              driver: driver.longhorn.io
              fsType: ext4
              volumeHandle: argocd-deploykf-pv
            claimRef:
              kind: PersistentVolumeClaim
              apiVersion: v1
              name: argocd-deploykf-plugin-assets
              namespace: argocd

    - name: Create DeployKF PersistentVolumeClaim
      k8s:
        state: present
        definition:
          kind: PersistentVolumeClaim
          apiVersion: v1
          metadata:
            name: argocd-deploykf-plugin-assets
            namespace: argocd
          spec:
            volumeName: argocd-deploykf-pv
            storageClassName: longhorn
            volumeMode: Filesystem
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi

    - name: Create DeployKF ConfigMap
      k8s:
        state: present
        definition:
          kind: ConfigMap
          apiVersion: v1
          metadata:
            name: argocd-deploykf-plugin
            namespace: argocd
          data:
            plugin.yaml: |
              {{ deploykf_plugin }}

    - name: Patch Argocd server
      k8s:
        state: patched
        namespace: argocd
        definition: "{{ deploykf_server_patch }}"
```
