### DISCUSSION TITLE
Installation Options for Built In Istio

### DISCUSSION THREAD

**Discussion by checomp** [deployKF/deployKF#249] [Questions & Answers] [answered]
Hi, 

I need to enable native sidecars for the istio install as outlined here https://istio.io/latest/blog/2023/native-sidecars/ . I defined updated chart values (1.22.4) according to the important notes here https://www.deploykf.org/releases/changelog-deploykf/?h=istio#0.1.5:~:text=Istio%3A-,While,-the%20default%20version . But I couldn't find anywhere where I can set additional installation values like ENABLE_NATIVE_SIDECARS.   Can anyone point me in the right direction??

Thanks

**Comment by checomp** [comment, marked as answer]
I had add it to the istio section in the override file like so:

```
  istio:
    valuesOverrides: |
      istio-daemon:
        pilot:
          env:
            ENABLE_NATIVE_SIDECARS: true
```
