### DISCUSSION TITLE
Is deployKf available to install in offline mode?

### DISCUSSION THREAD

**Discussion by shelleyo9** [deployKF/deployKF#60] [Questions & Answers] [answered]
Hey, I’m trying to using deployKF to deploy kubeflow on openshift4 with argocd already installed in a disconnected environment. When applying app-of-apps.yaml, the Application shows error like :error get https://api.github.com/repos/deployKF/releases/tags/${source_version}, i/o timeout. I’ve already change the repoURL to private repo, I’m wondering if this release get is configurable or not. Reeeeally appreciate your help!!

**Comment by thesuperzapper** [comment, marked as answer]
@shelleyo9 currently, if you want to deploy in a truly isolated environment (i.e. no GitHub access), you won't be able to use the `source_version` feature of the ArgoCD Plugin.

However, you can work around this by using the [`source_path`](https://github.com/deployKF/deployKF/tree/main/argocd-plugin#plugin-parameters) feature of the plugin:

1. Download the latest `deploykf-X.X.X-generator.zip` file from the [GitHub releases](https://github.com/deployKF/deployKF/releases)
2. Upload the zip file into a git repo (which your ArgoCD can see)
3. Update your app-of-apps to look something like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploykf-app-of-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: deploykf-app-of-apps
    app.kubernetes.io/part-of: deploykf
spec:
  project: "default"
  source:

    ## source git repo configuration
    ##
    repoURL: "__YOUR_GIT_REPO_URL__"
    targetRevision: "__YOUR_GIT_REPO_BRANCH__"
    path: "."

    ## plugin configuration
    ##
    plugin:
      name: "deploykf"
      parameters:

        ## the deployKF generator path
        ##
        - name: "source_path"
          string: "./path/in/repo/to/deploykf-X.X.X-generator.zip"

        ## paths to values files within the `repoURL` repository
        ##
        - name: "values_files"
          array:
            - ...

        ## a string containing the contents of a values file
        ##
        - name: "values"
          string: |
            ...

  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"
```

---

Also note, if you are running a very isolated cluster, you will probably need to mirror the container images into your private registry (as the manifests images from DockerHub, GHCR, etc. by default).

We are planning to make a script to generate the list of images to mirror, and example values to override all the image registries with a private one, but if you end up doing this yourself, please share your approach.
