### DISCUSSION TITLE
Is it possible to define group-based access to a minio bucket?

### DISCUSSION THREAD

**Discussion by Diddy42** [deployKF/deployKF#64] [Questions & Answers] [answered]
Hi, great project!

Let's say I defined an additional bucket `datasets` with the value `deploykf_opt.deploykf_minio.buckets`.

I also have a group of users called `machine-learning`, defined with the value `deploykf_core.deploykf_profiles_generator.groups`.

Can I set some value so that the users of the group `machine-learning` have access to the bucket `datasets`?

Unless I'm missing something about minio policies, this cannot be done through `deploykf_opt.deploykf_minio.policies`, but I'd be happy to be proven wrong ^^

**Comment by thesuperzapper** [comment, marked as answer]
@Diddy42 First, I want to say that the embedded MinIO is NOT currently intended for production usage, it's meant to allow users to test deployKF anywhere, before they [connect to a more robust S3-like object store](https://www.deploykf.org/guides/tools/external-object-store/). 

_(That is NOT to say you can't set up your own MinIO Object Store, and connect deployKF with it)_

---

While it's a bit dangerous to encourage usage of the embedded MinIO, I am open to accepting a contribution that lets you define `extraPolicyStatements`, as we don't currently provide a way to extend the policies we automatically generate for each user defined in `deploykf_core.deploykf_profiles_generator.users`.

For example, we could add a value like `deploykf_opt.deploykf_minio.extraPolicyStatements`:

```yaml
deploykf_opt:
  deploykf_minio:

    ## a list of extra policy statements to add to the default policy
    ## generated for each user in `deploykf_core.deploykf_profiles_generator.users`
    extraPolicyStatements:

      ## additional policy statements for 'user-1' 
      - user: user-1
        statements:
          ## allow 'user-1' to see MY_BUCKET_NAME
          - Effect: Allow
            Action:
              - s3:GetBucketLocation
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::MY_BUCKET_NAME

      ## additional policy statements for each member of 'team-1' group
      - group: team-1
        statements:
          ## allow members of 'team-1' to see MY_BUCKET_NAME
          - Effect: Allow
            Action:
              - s3:GetBucketLocation
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::MY_BUCKET_NAME
          
          ## allow members of 'team-1' to read/write under MY_BUCKET_NAME/some-prefix/*
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource:
              - arn:aws:s3:::MY_BUCKET_NAME/some-prefix/*
```

The way this would be implemented would be by extending the automatically generated `deploykf_opt.deploykf_minio.policies` which are defined here:

https://github.com/deployKF/deployKF/blob/80b64830530c9217adfdd40454c412212b2305c0/generator/templates/manifests/deploykf-opt/deploykf-minio/values.yaml#L210-L240

__Some of the important templates which are called in the above section are:__

- [`runtime/deploykf_profiles__users_id_mapping_json`](https://github.com/deployKF/deployKF/blob/v0.1.3/generator/helpers/deploykf-profiles.tpl#L4-L41): 
    - a JSON mapping from `user` -> `user info` (needed to get the `email` of the user, for the policy name)
- [`kubeflow_pipelines.object_store.user.minio_policy`](https://github.com/deployKF/deployKF/blob/v0.1.3/generator/helpers/kubeflow-pipelines--object-store.tpl#L246-L280): 
    - the actual per-user IAM policy template (this would need extending with the capability to take `extra_statements`)

__You would also need to use the `group` -> `user` mapping JSON template, to get the list of users in a group:__

- [`runtime/deploykf_profiles__groups_id_mapping_json`](https://github.com/deployKF/deployKF/blob/v0.1.3/generator/helpers/deploykf-profiles.tpl#L43-L75)
