### ISSUE TITLE
add values for `targetMemoryUtilizationPercentage` and resources to istio gateway

### ISSUE THREAD

**Issue by D1sko** [deployKF/deployKF#117]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This request is NOT specific to the CLI. (If so, please open an issue on the [CLI repo](https://github.com/deployKF/cli/issues))

### Motivation

* In my Istio deployment i am using targetMemoryUtilizationPercentage as an autoscaling metric and i could easily see others doing this as well for high utilization gateways
* Having the option to customize limits would be great as well since 1024m (even though the default) is low for a high utilization gateway

### Are you willing & able to help?

- [X] I am able to submit a PR!
- [ ] I can help test the feature!

**Comment by thesuperzapper** [comment]
@D1sko Thanks for raising PR https://github.com/deployKF/deployKF/pull/119, until that PR is merged, I just want to highlight you can set these values using the existing "values overrides" feature.

__WARNING:__ using `targetMemoryUtilizationPercentage` requires using version `1.21.0` of the Istio chart, and I have not tested istio `1.21` with deployKF `0.1.4` yet.

If you are willing to risk it, here are the deployKF values to set these values with "values overrides":

```yaml
deploykf_dependencies:
  istio:

    charts:
      ## WARNING: these versions need to be aligned with the gateway version
      ## WARNING: updating istio might require you to restart your pods (so they get the new sidecar version)
      istioBase:
        version: 1.21.0
      istioDaemon:
        version: 1.21.0

deploykf_core:
  deploykf_istio_gateway:

    valuesOverrides: |
      gateway:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 2000m
            memory: 1024Mi
      
        autoscaling:
          targetMemoryUtilizationPercentage: XXXXX

    charts:
      istioGateway:
        ## WARNING: the `targetMemoryUtilizationPercentage` value was only added in the 1.21.0 chart version
        ##          so you will probably have to upgrade the overall istio also
        version: 1.21.0
```
