### ISSUE TITLE
Cannot access notebook created in my namespace

### ISSUE THREAD

**Issue by bgalvao** [deployKF/deployKF#120]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT specific to the CLI. (If so, please open an issue on the [CLI repo](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.4

### Kubernetes Version

```shell
Client Version: v1.28.8
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1-eks-b9c9ed7
```

### Description

I was trying to access a notebook I created, but surprisingly I was denied access to the notebook in my own namespace / profile.

![image](https://github.com/deployKF/deployKF/assets/17158288/fb8eddc3-ba48-4178-bab2-647188425ff2)

### Relevant Logs

```shell
Don't know where to look for relevant logs (some kyverno pod?), but I'm happy to be instructed and update this field with the relevant logs.
```

### deployKF Values (Optional)

```yaml
deploykf_auth:
  dex:
    connectors:
      - type: google
        id: google
        name: Google
        config: (...)

deploykf_profiles_generator:
  users:
    - id: bernardo-galvao
      email: "bernardo.galvao@pumpinai.com"
  profiles:
    - name: bernardo-galvao
      members:
        - user: bernardo-galvao
          access:
            role: edit
            notebookAccess: true
```

**Comment by bgalvao** [comment]
Additional context:
* using EKS
* managing access via Access Entries of EKS
* my user is not in the `aws-auth` ConfigMap

I think fixing that should fix the issue

**Comment by thesuperzapper** [comment]
@bgalvao are the notebooks the only places you are seeing "RBAC: Access Denied" errors?

For example, is this user able to browse the dashboard in that namespace, and view pipelines?

**Comment by bgalvao** [comment]
Hey @thesuperzapper, yes that is the only place.

* I can navigate to volumes, create volumes.
* Can navigate to Tensorboard

(I disabled KF pipelines for this instance of deployKF as my team does not use them.)

**Comment by bgalvao** [comment]
@thesuperzapper 
Big thanks to @gilcardoai for finding the solution. (Expand for diffs)

<details><summary>ns-owner-access-istio AuthorizationPolicy</summary>

```diff
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  annotations:
    role: admin
    user: admin@example.com
  name: ns-owner-access-istio
  namespace: bernardo-galvao
spec:
  rules:
    - when:
        - key: request.headers[kubeflow-userid]
          values:
-           - admin@example.com
+           - bernardo.galvao@pumpkinai.com
    - when:
        - key: source.namespace
          values:
            - bernardo-galvao
    - to:
        - operation:
            paths:
              - /healthz
              - /metrics
              - /wait-for-drain
    - from:
        - source:
            principals:
              - cluster.local/ns/kubeflow/sa/notebook-controller-service-account
      to:
        - operation:
            methods:
              - GET
            paths:
              - '*/api/kernels'
```

</details> 


<details><summary>Profile</summary>
<p>

```diff
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  finalizers:
    - profile-finalizer
  name: bernardo-galvao
spec:
  owner:
    kind: User
-   name: admin@example.com
+   name: bernardo.galvao@pumpkinai.com
```

</p>
</details> 

---

That being said, I have not looked into the internals of deployKF, but there seems to be an override Authorization policy that is perhaps supposed to be updated with an authorize action for my user (`bernardo.galvao@pumpkinai.com`), because all it has is a `DENY` action for the only email that was present before as the owner of the Profile: `admin@example.com`:

<details><summary>ns-owner-access-istio--override</summary>
<p>

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ns-owner-access-istio--override
  namespace: bernardo-galvao
spec:
  action: DENY
  rules:
    - from:
        - source:
            notPrincipals:
              - cluster.local/ns/deploykf-istio-gateway/sa/deploykf-gateway
      when:
        - key: request.headers[kubeflow-userid]
          values:
            - admin@example.com
``` 

</p>
</details> 


Also, when I tried to add my own email as the ownerEmail of profile, like this

```yaml
deploykf_profiles_generator:
  users:
    - id: bernardo-galvao
      email: "bernardo.galvao@pumpkinai.com"
  profiles:
    - name: bernardo-galvao
      ownerEmail: bernardo.galvao@pumpkinai.com
      members:
        - user: bernardo-galvao
          access:
            role: edit
            notebookAccess: true
```

that is not something that is allowed:

```
(profile name: 'bernardo-galvao') may not include users with same email as profile owner, but user 'bernardo-galvao' at index 0 has email 'bernardo.galvao@pumpkinai.com'
```

meaning that it uses the default admin@example.com.

---

Sorry for the long comment, I wanted to be as detailed as possible. The project deployKF is awesome and I want to see it grow!
