### ISSUE TITLE
[custom dashboard] Cannot add new link

### ISSUE THREAD

**Issue by MLOpsGuy** [deployKF/deployKF#168]
Hi @thesuperzapper , I don't know if it is the good repo to ask this, but I will try 🙃. 

I would like to custom the dashboard. For this, I added :

```yaml
      documentationItems:
        - text: deployKF Website
          desc: The tool that deployed your ML platform!
          link: https://github.com/deployKF/deployKF
        - text: POUET
          desc: Amazing web site
          link: https://www.pouet.net/
```
in `deploykf_core.deploykf_dashboard.navigation` in `generator/default_values.yaml`.

I deployed deployKF with ArgoCD and the official GitHub repo.

Do you have any idea why `POUET` website didn't appear in the dashboard?

_PS: Same thing for `externalLinks`:_

```yaml
      externalLinks:
        - text: POUET
          url: "/pouet/"
          icon: image:blur-linear
```

**Comment by thesuperzapper** [comment]
@MLOpsGuy you should not be editing the `default_values.yaml`, you should be seting the values either using the `values` or `values_files` plugin parameters.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploykf-app-of-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: deploykf-app-of-apps
    app.kubernetes.io/part-of: deploykf
spec:
  project: "default"
  source:

    ## source git repo configuration
    ##
    repoURL: "https://github.com/<EXAMPLE_ORG>/<EXAMPLE_REPO>.git"
    targetRevision: "main"
    path: "."

    ## plugin configuration
    ##
    plugin:
      name: "deploykf"
      parameters:

        ## the deployKF generator version
        ##
        - name: "source_version"
          string: "0.1.5"

        ## paths to values files within the `repoURL` repository
        ##
        - name: "values_files"
          array:
            - "./sample-values-0.1.5.yaml"
            - "./values-1.yaml"
            - "./values-2.yaml"

        ## a string containing the contents of a values file
        ##  - we are not using this in this example
        ##  - values defined here have the highest precedence
        ##
        #- name: "values"
        #  string: |
        #    ...
        #    values file contents
        #    ...

  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"
```


See the following guides for more info: https://www.deploykf.org/guides/values/
