### ISSUE TITLE
Istio outbound connection not working properly on EKS IPV6-only clusters

### ISSUE THREAD

**Issue by jdraymon** [deployKF/deployKF#170]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.5

### Kubernetes Distribution

EKS

### Kubernetes Version

```shell
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b
```

### Description

While trying to deploy deployKF to an EKS IPv6-only cluster, the Dex container fails to start when attempting to make an outbound connection (specifically to fetch the Google Auth OIDC configuration at https://accounts.google.com/.well-known/openid-configuration):

### Relevant Logs

```shell
failed to initialize server: server: Failed to open connector google-auth: failed to open connector: failed to create connector google-auth: failed to get provider: Get "https://accounts.google.com/.well-known/openid-configuration": read tcp [<Pod IPv6>]:44268->[2607:f8b0:400e:c0c::54]:443: read: connection reset by peer
```
```


### deployKF Values (Optional)

```yaml
deploykf_auth:
  dex:
    connectors:
      - type: google
        id: google-auth
        name: SSO
        config:
          clientID: <id>.apps.googleusercontent.com
          clientSecret: <secret>
          redirectURI: https://kubeflow.example.com/dex/callback
```
