### ISSUE TITLE
Oauth2-proxy: Multiple cookies are required for this session as it exceeds the cookie limit. Headers too big

### ISSUE THREAD

**Issue by antoniogmartin** [deployKF/deployKF#171]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.4

### Kubernetes Distribution

On premise / Local

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.7+rke2r1", GitCommit:"c8dcb00be9961ec36d141d2e4103f85f92bcf291", GitTreeState:"clean", BuildDate:"2024-02-14T16:35:57Z", GoVersion:"go1.21.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

### Description

Hi,

When I try to sign in deploykf using LDAP option in dex. It  fails and gives the following HTTP error:

`HTTP error 431: headers too big
`

Oauth2-proxy  shows the following warning:

`[2024/06/04 06:53:23] [session_store.go:170] WARNING: Multiple cookies are required for this session as it exceeds the 4kb cookie limit. Please use server side session storage (eg. Redis) instead.`

After some research I've found there are two ways of solving this...

1. At https://github.com/oauth2-proxy/oauth2-proxy/issues/644#issuecomment-1261223660 @BrianHuf posted that It worked for him to add the following flags to Oauth2-proxy:

`--session-cookie-minimal true   --scope openid email`

2. At  https://github.com/oauth2-proxy/oauth2-proxy/issues/644. It is suggested as well to  activate redis storage in oauth2-proxy configuration.

`
redis:
  enabled: true
sessionStorage:
  type: redis
`

I've made changes into  sample_values.yaml:

```
      redis:
        enabled: true
      sessionStorage:
        type: redis
        redis:
          clientType: standalone
```

and    templates/manifests/deploykf-core/deploykf-auth
```
  redis:
    enabled: {{< .Values.deploykf_core.deploykf_auth.oauth2Proxy.redis.enabled | false >}}
  sessionStorage:
    type: {{< .Values.deploykf_core.deploykf_auth.oauth2Proxy.redis.type | cookie >}}
    redis:
      clientType: {{< .Values.deploykf_core.deploykf_auth.oauth2Proxy.redis.clientType | standalone >}}
```

with no changes into oauth2-proxy configuration..

 My question is...How should I perform these changes?

### Relevant Logs

```shell
The below exmple  includes an array of 83 groups, others users may have around 70 groups. In any case is pretty common to have +70 groups..

127.0.0.6 - 5178794a-ac6a-4848-9225-56999eeb9622 - - [2024/06/04 06:53:21] 10.242.190.72:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.28" 200 2 0.000
10.165.196.201 - 04cd2995-5c54-4653-970d-3e89ea817472 - anguzman@theworkshop.com [2024/06/04 06:53:23] [AuthSuccess] Authenticated via OAuth2: Session{email:anguzman@theworkshop.com user:ClVDTj1BbnRvbmlvIEd1em1hbixPVT1JVE8sT1U9VXNlcnMsT1U9UFRBLE9VPU1BTCxPVT1PZmZpY2VzLERDPWNvcnAsREM9a2F6b290ZWssREM9Y29tEgRsZGFw PreferredUsername:689914341 token:true id_token:true created:2024-06-04 06:53:23.824810466 +0000 UTC m=+59741.422276144 expires:2024-06-04 07:53:22.824118199 +0000 UTC m=+63340.421583318 refresh_token:true groups:[ <group_1> ....<group_2> .... <group_83>]}
```

### deployKF Values (Optional)

```yaml
redis:
        enabled: true
      sessionStorage:
        type: redis
        redis:
          clientType: standalone
```

**Comment by thesuperzapper** [comment]
@antoniogmartin we aren't able to use `--session-cookie-minimal true` because we use refresh tokens (to prevent users having to log in again). While we could use a Redis backend, that would require us to add a Redis deployment to deployKF. We can consider doing that if other solutions don't fix this for you.

---

The core of your problem is that your LDAP connector is returning too many groups, if you follow the default [LDAP Example](https://www.deploykf.org/guides/platform/deploykf-authentication/#active-directory-ldap) you will end up with something that looks like this:

```yaml
deploykf_core:
  deploykf_auth:
    dex:
      connectors:
        - type: ldap
          id: ldap
          name: LDAP
          config:
            ## the LDAP server URL and port
            host: ldap.example.com:636

            ## if we should skip TLS certificate verification
            ## WARNING: this is insecure, prefer to use `rootCAData`
            insecureSkipVerify: false

            ## a base64 encoded PEM file with your root CA certificate
            #rootCAData: ""

            ## the credentials to use for searching the directory
            ## NOTE: not required if anonymous bind is allowed
            #bindDN: uid=Administrator,cn=Users,dc=example,dc=com
            #bindPW: password

            ## text used in password-prompt box
            usernamePrompt: "Username"

            ## how users are searched for, based on the provided username
            userSearch:

              ## base search from
              baseDN: cn=Users,dc=example,dc=com

              ## an additional search filter to apply
              filter: "(objectClass=person)"

              ## how to map user attributes
              username: uid
              idAttr: uid
              emailAttr: mail
              nameAttr: name

            ## how groups are searched for, based on the found user
            groupSearch:
              ## base search from
              baseDN: cn=Groups,dc=example,dc=com

              ## an additional search filter to apply
              ## NOTE: you may need to limit the search to prevent a large number of results
              filter: "(objectClass=group)"

              ## list of user-attribute to group-attribute pairs
              ## the value of the found user's `userAttr` must be one of the group's `groupAttr`
              userMatchers:
                - userAttr: uid
                  groupAttr: member

              ## how to map group attributes
              nameAttr: cn
```

We need to make `groupSearch.filter` more restrictive to reduce the number of groups returned.

Because deployKF doesn't use the groups right now (only the user's email), you can either just make your group filter match nothing, or only the groups that you plan to use when deployKF starts supporting them. You might extend the `filter: "(objectClass=group)"` to also filter by the name of the group (or something else in your AD tree).

For example: `filter: "(&(objectClass=group)(cn=*deployKF*))"` will only match groups which contain `"deployKF"` in their `CN`.

---

Note, separate to this, if you want to ensure only members of a specific group are able to log in, you will need to do that in the `userSearch.filter`, with something like this:

```yaml
userSearch:
  baseDN: cn=Users,dc=example,dc=com
  filter: "(&(objectClass=person)(memberOf=cn=deploykf,ou=Groups,dc=example,dc=com))"
```

This pattern could be extended to support multiple groups by using `(|(memberOf=...)(memberOf=...))`.
