### ISSUE TITLE
OAuth2  could not create provider data

### ISSUE THREAD

**Issue by haiminh2001** [deployKF/deployKF#185]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.5

### Kubernetes Distribution

v1.26.6+k3s1

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", Go
Version:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6+k3s1", GitCommit:"3b1919b0d55811707bd1168f0abf11cccc656c26", GitTreeState:"clean", BuildDate:"2023-06-26T17:51:14Z
", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
```

### Description

I disable istio dependency and use my pre-installed verision of istio (v1.19). I check the default values of deployKF's istio version and I acknowledged that DNS proxy should be turned on. But oauth still seem to not able to connect to dex via istio ingress. My deployKF values relevant to istio is attached below.
I add  DNS proxy by adding this annotations to oauth2 pod:
```
    proxy.istio.io/config: |  # YAML multi-line string definition
       proxyMetadata:
         ISTIO_META_DNS_CAPTURE: "true"
         ISTIO_META_DNS_AUTO_ALLOCATE: "true"
```

### Relevant Logs

```shell
[2024/07/23 10:58:39] [provider.go:55] Performing OIDC Discovery...
[2024/07/23 10:58:39] [main.go:58] ERROR: Failed to initialise OAuth2 Proxy: error initialising provider: could not create provider data: error building OIDC ProviderVerifier: could not get verifier builder: error while discovery OIDC configuration: failed to discover OIDC configuration: error performing request: Get "https://deploykf.example.com:8443/dex/.well-known/openid-configuration": EOF
```

### deployKF Values (Optional)

```yaml
deploykf_istio_gateway:
    namespace: istio-system
    charts:
      istioGateway:
        enabled: false
    gateway:
      selectorLabels:
        app: istio-gateway
    gatewayDeployment:
      serviceAccount:
        name: istio-gateway
    gatewayService:
      name: istio-gateway
      type: NodePort
```

**Comment by thesuperzapper** [comment]
@haiminh2001 did you set all the configs listed on the [use existing istio](https://www.deploykf.org/guides/dependencies/istio/#use-an-existing-istio-installation) guide?

If you are installing Istio with it's helm chart, here are the required values:

```yaml
meshConfig:
  defaultConfig:
    holdApplicationUntilProxyStarts: true
    proxyMetadata:
      ISTIO_META_DNS_AUTO_ALLOCATE: "true"
      ISTIO_META_DNS_CAPTURE: "true"

sidecarInjectorWebhook:
  enableNamespacesByDefault: false
```

These need to be set at the __cluster__ level, not just on oauth2-proxy pods.

---

Also, if you are [bringing your own Istio gateway deployment](https://www.deploykf.org/guides/dependencies/istio/#use-an-existing-gateway-deployment), make sure you are not using the ports that deployKF is listening on for any other services.
