### ISSUE TITLE
secrets "mlpipeline-minio-artifact" not found

### ISSUE THREAD

**Issue by haiminh2001** [deployKF/deployKF#192]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.5

### Kubernetes Distribution

v1.26.6+k3s1

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", Go
Version:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6+k3s1", GitCommit:"3b1919b0d55811707bd1168f0abf11cccc656c26", GitTreeState:"clean", BuildDate:"2023-06-26T17:51:14Z
", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
```

### Description

My kfpv2 pipeline failed with this log:
```
I0808 09:34:29.856606      69 cache.go:116] Connecting to cache endpoint ml-pipeline.kubeflow.svc.cluster.local:8887
I0808 09:34:30.213371      69 launcher_v2.go:151] publish success.
F0808 09:34:30.213465      69 main.go:49] failed to execute component: failed to fetch non default buckets: failed to open bucket for output artifact "train_path" with uri "minio://kubeflow-pipelines/v2/artifacts/team-1-prod/trainingadspipeline/667d6ccb-5da0-45c8-b0e0-a0ae76b2b563/get-data/dataset_folder": Failed to open bucket "kubeflow-pipelines": Failed to get minio credential: Failed to get MinIO credential from secret name="mlpipeline-minio-artifact" namespace="team-1-prod": secrets "mlpipeline-minio-artifact" not found
time="2024-08-08T09:34:30.824Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
time="2024-08-08T09:34:31.765Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
```
And I saw this config in version 0.1.3:
```
      ## apply fixes to make MinIO work with KFP v2
      ##  - these fixes are needed because KFP v2 uses hard-coded configs for MinIO
      ##    https://github.com/kubeflow/pipelines/issues/9689
      ##  - if true:
      ##     - the name of all cloned object store auth secrets in profiles becomes "mlpipeline-minio-artifact"
      ##     - the key names used in generated minio auth secrets becomes "accesskey" and "secretkey"
      ##     - the 'kfp-launcher' containers in workflow pods are patched at runtime to set:
      ##        - `MINIO_SERVICE_SERVICE_HOST` and `MINIO_SERVICE_SERVICE_PORT`
      ##        - `ML_PIPELINE_SERVICE_HOST` and `ML_PIPELINE_SERVICE_PORT_GRPC`
      ##     - the value of `kubeflow_tools.pipelines.objectStore.useExternal` must be false
      ##
      minioFix: false
```
[The issue referenced](https://github.com/kubeflow/pipelines/issues/9689) is still opened but the config to fix it no longer exists in version 0.1.5. It looks like the issue was not fixed, but the config is gone. Did deployKF fixed it by itself ? If so how did you fixed it and can you give a guess why I am still facing this issue ? Thank you in advance for your support.

### Relevant Logs

The downstream component is failed to authenticate to Minio but the upstream that produced the dataset still successfully uploaded the artifacts to the same Minio:
```
I0808 09:25:14.221036      55 cache.go:116] Connecting to cache endpoint ml-pipeline.kubeflow.svc.cluster.local:8887
Added `minio-local` successfully.
`minio-local/dev/labels/NEW_1153_0567.txt` -> `/minio/kubeflow-pipelines/v2/artifacts/team-1-prod/trainingadspipeline/667d6ccb-5da0-45c8-b0e0-a0ae76b2b563/get-data/dataset_folder/dev/labels/NEW_1153_0567.txt`
`minio-local/dev/images/NEW_1153_0567.jpg` -> `/minio/kubeflow-pipelines/v2/artifacts/team-1-prod/trainingadspipeline/667d6ccb-5da0-45c8-b0e0-a0ae76b2b563/get-data/dataset_folder/dev/images/NEW_1153_0567.jpg`
Total: 218.04 KiB, Transferred: 218.04 KiB, Speed: 331.10 KiB/s
I0808 09:25:20.038687      55 launcher_v2.go:680] output metadata file does not exist in /tmp/kfp_outputs/output_metadata.json
I0808 09:25:20.376641      55 object_store.go:258] uploadFile(localFilePath="/minio/kubeflow-pipelines/v2/artifacts/team-1-prod/trainingadspipeline/667d6ccb-5da0-45c8-b0e0-a0ae76b2b563/get-data/dataset_folder/dev/images/NEW_1153_0567.jpg", blobFilePath="get-data/dataset_folder/dev/images/NEW_1153_0567.jpg")
I0808 09:25:20.385197      55 object_store.go:258] uploadFile(localFilePath="/minio/kubeflow-pipelines/v2/artifacts/team-1-prod/trainingadspipeline/667d6ccb-5da0-45c8-b0e0-a0ae76b2b563/get-data/dataset_folder/dev/labels/NEW_1153_0567.txt", blobFilePath="get-data/dataset_folder/dev/labels/NEW_1153_0567.txt")
I0808 09:25:21.391699      55 launcher_v2.go:151] publish success.
```

**Comment by haiminh2001** [comment]
When I tried to workaround by creating the missing secret, I get this error:
```
I0809 01:38:26.139478      68 cache.go:116] Connecting to cache endpoint ml-pipeline.kubeflow.svc.cluster.local:8887
I0809 01:38:27.305366      68 object_store.go:314] Cannot detect minio-service in the same namespace, default to minio-service.kubeflow:9000 as MinIO endpoint.
I0809 01:38:28.345807      68 launcher_v2.go:151] publish success.
F0809 01:38:28.345921      68 main.go:49] failed to execute component: failed to download input artifact "train_path" from remote storage URI "minio://kubeflow-pipelines/v2/artifacts/team-1-prod/trainingadspipeline/667d6ccb-5da0-45c8-b0e0-a0ae76b2b563/get-data/dataset_folder": failed to list objects in remote storage "v2/artifacts/team-1-prod/trainingadspipeline/667d6ccb-5da0-45c8-b0e0-a0ae76b2b563/get-data/dataset_folder": blob (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
time="2024-08-09T01:38:29.114Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
time="2024-08-09T01:38:30.057Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
```
It seems to be the issue that the ```minioFix``` supposed to fix persists in version 0.1.5.

**Comment by thesuperzapper** [comment]
@haiminh2001 can you confirm if this affects all pipelines or only some?

If only some, can you please share a simple one that causes it?

Also, if you upgraded from an earlier version, make sure you followed the steps in the upgrade guide (and removed some of the sample values which conflict with 0.1.5).

**Comment by AnteWall** [comment]
We have also encountered this issue with all our V2 pipelines when components are sending `Input` of any type into another component. V1 pipelines are however still working correctly

**Comment by thesuperzapper** [comment]
Can @AnteWall or someone else, please share a basic pipeline example that does not work?

**Comment by AnteWall** [comment]
So we got it to work yesterday after some deep diving into the code. 

There were 2 things caused by the same thing. We have a S3 trough CephFS, which is a url like `s3://s3.customdomain.com` but we always got "minio://..." instead. This was due to a check for `s3.*amazonaws.com` regex check to see if it's a S3. Both in the deployKF chart and in Kubeflow Pipelines code. So we changed our custom url to be `s3.amazonaws.com.customdomain.com` and now it works! 

However it only works if we disable cache. If it's using cache it's still sending a minio:// url to the argo job and then it can't download the file(s) from cache. So we are still trying to figure out how/if we can change that to a s3:// prefix instead of a minio becuase then we believe we can get that to work also

**Comment by thesuperzapper** [comment]
> There were 2 things caused by the same thing. We have a S3 trough CephFS, which is a url like `s3://s3.customdomain.com` but we always got "minio://..." instead. This was due to a check for `s3.*amazonaws.com` regex check to see if it's a S3. Both in the deployKF chart and in Kubeflow Pipelines code. So we changed our custom url to be `s3.amazonaws.com.customdomain.com` and now it works!

@AnteWall that's good to hear, but I think for users who are actually using MinIO, there might still be a problem when a `Dataset` type input is passed to a pipeline step.

I think the issue will be that the query-string [`?region={bucket_region}&endpoint={endpoint}...`](https://github.com/deployKF/deployKF/blob/v0.1.5/generator/default_values.yaml#L1924) is not being picked up in that specific case.

The problem is that deployKF 0.1.5 relies on the behavior of the [`gcloud.dev` library](https://gocloud.dev/howto/blob/#s3-compatible) which is to use the `AWS_ACCESS_KEY_ID`/`AWS_SECRET_ACCESS_KEY` env-vars when `&endpoint=` is set (read more in https://github.com/deployKF/deployKF/pull/122), rather than [falling back to the `mlpipeline-minio-artifact` Secret](https://github.com/kubeflow/pipelines/blob/2.1.0/backend/src/v2/objectstore/object_store.go#L317-L323).

There was an upstream PR to preserve the query strings for for the pipeline root https://github.com/kubeflow/pipelines/pull/10319, but I think the case of `Dataset` input types were forgotten, so it's just seeing `minio://xxxxx` (with no `?endpoint=xxxx` query), and so is falling back to the `mlpipeline-minio-artifact` secret.

We probably need to do something similar to https://github.com/kubeflow/pipelines/pull/10319, we just need to find where the Dataset input code lives, and patch it in the [deployKF fork of Kubeflow Pipelines](https://github.com/deployKF/kubeflow-pipelines).

---

> However it only works if we disable cache. If it's using cache it's still sending a minio:// url to the argo job and then it can't download the file(s) from cache. So we are still trying to figure out how/if we can change that to a s3:// prefix instead of a minio becuase then we believe we can get that to work also

You can turn off caching for a specific V2 step, or you could go nuclear and delete the cache information from the KFP MySQL database.

**Comment by haiminh2001** [comment]
> > There were 2 things caused by the same thing. We have a S3 trough CephFS, which is a url like `s3://s3.customdomain.com` but we always got "minio://..." instead. This was due to a check for `s3.*amazonaws.com` regex check to see if it's a S3. Both in the deployKF chart and in Kubeflow Pipelines code. So we changed our custom url to be `s3.amazonaws.com.customdomain.com` and now it works!
> 
> @AnteWall that's good to hear, but I think for users who are actually using MinIO, there might still be a problem when a `Dataset` type input is passed to a pipeline step.
> 
> I think the issue will be that the query-string [`?region={bucket_region}&endpoint={endpoint}...`](https://github.com/deployKF/deployKF/blob/v0.1.5/generator/default_values.yaml#L1924) is not being picked up in that specific case.
> 
> The problem is that deployKF 0.1.5 relies on the behavior of the [`gcloud.dev` library](https://gocloud.dev/howto/blob/#s3-compatible) which is to use the `AWS_ACCESS_KEY_ID`/`AWS_SECRET_ACCESS_KEY` env-vars when `&endpoint=` is set (read more in #122), rather than [falling back to the `mlpipeline-minio-artifact` Secret](https://github.com/kubeflow/pipelines/blob/2.1.0/backend/src/v2/objectstore/object_store.go#L317-L323).
> 
> There was an upstream PR to preserve the query strings for for the pipeline root [kubeflow/pipelines#10319](https://github.com/kubeflow/pipelines/pull/10319), but I think the case of `Dataset` input types were forgotten, so it's just seeing `minio://xxxxx` (with no `?endpoint=xxxx` query), and so is falling back to the `mlpipeline-minio-artifact` secret.
> 
> We probably need to do something similar to [kubeflow/pipelines#10319](https://github.com/kubeflow/pipelines/pull/10319), we just need to find where the Dataset input code lives, and patch it in the [deployKF fork of Kubeflow Pipelines](https://github.com/deployKF/kubeflow-pipelines).
> 
> > However it only works if we disable cache. If it's using cache it's still sending a minio:// url to the argo job and then it can't download the file(s) from cache. So we are still trying to figure out how/if we can change that to a s3:// prefix instead of a minio becuase then we believe we can get that to work also
> 
> You can turn off caching for a specific V2 step, or you could go nuclear and delete the cache information from the KFP MySQL database.

Thank you @thesuperzapper for your clear explanation, so that means at the moment there is no way to use ```Dataset``` input types using Minio storage ?

**Comment by thesuperzapper** [comment]
@haiminh2001 I'm still yet to find an actual example which doesn't work in my test clusters.

Do you have a pipeline which I can try that doesn't work?

**Comment by haiminh2001** [comment]
> @haiminh2001 I'm still yet to find an actual example which doesn't work in my test clusters.
> 
> Do you have a pipeline which I can try that doesn't work?

This is my pipeline.yaml
```
# PIPELINE DEFINITION
# Name: trainingadspipeline
# Inputs:
#    train_path: str

components:
  comp-get-data:
    executorLabel: exec-get-data
    inputDefinitions:
      parameters:
        data_uri:
          parameterType: STRING
    outputDefinitions:
      artifacts:
        dataset_folder:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
  comp-train:
    executorLabel: exec-train
    inputDefinitions:
      artifacts:
        train_path:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
    outputDefinitions:
      artifacts:
        model:
          artifactType:
            schemaTitle: system.Model
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-get-data:
      container:
        args:
        - -c
        - mc config host add minio-local http://minio-mlops.deploykf-minio.svc.cluster.local:80
          admin admin123 && mc cp --recursive minio-local/{{$.inputs.parameters['data_uri']}}
          {{$.outputs.artifacts['dataset_folder'].path}}
        command:
        - sh
        env:
        - name: test
          value: hehe
        image: minio/mc
    exec-train:
      container:
        args:
        - --train-path
        - '{{$.inputs.artifacts[''train_path''].path}}'
        - --val-path
        - '{{$.inputs.artifacts[''train_path''].path}}'
        - --model
        - yolov8l
        - --cfg
        - ultralytics/cfg/ads.yaml
        - --devices=0
        command:
        - python
        - train.py
        image: my-registry/myclip:dev
        resources:
          accelerator:
            count: '2'
            type: nvidia.com/gpu
pipelineInfo:
  name: trainingadspipeline
root:
  dag:
    tasks:
      get-data:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-get-data
        inputs:
          parameters:
            data_uri:
              componentInputParameter: train_path
        taskInfo:
          name: get-data
      train:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-train
        dependentTasks:
        - get-data
        inputs:
          artifacts:
            train_path:
              taskOutputArtifact:
                outputArtifactKey: dataset_folder
                producerTask: get-data
        taskInfo:
          name: train
  inputDefinitions:
    parameters:
      train_path:
        parameterType: STRING
      val_path:
        parameterType: STRING
schemaVersion: 2.1.0
sdkVersion: kfp-2.8.0
```


> There was an upstream PR to preserve the query strings for for the pipeline root https://github.com/kubeflow/pipelines/pull/10319, but I think the case of Dataset input types were forgotten, so it's just seeing minio://xxxxx (with no ?endpoint=xxxx query), and so is falling back to the mlpipeline-minio-artifact secret

You mentioned that input of type ```Dataset``` is falling back to the ```mlpipeline-minio-artifact``` secret which does not exists. If I understand it correctly, you should be able to reproduce the issue with any pipeline that has a step having an input of type ```Dataset``` and is stored in a Minio storage.  Is there anything I misunderstood ?
