### ISSUE TITLE
`kubeflow_tools.notebooks.images.notebookController.tag` value does not work

### ISSUE THREAD

**Issue by kotari** [deployKF/deployKF#193]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.5

### Kubernetes Distribution

EKS

### Kubernetes Version

```shell
1.30.x
```

### Description

Notebook controller version mismatch

### Relevant Logs

```shell
generator/templates/manifests/kubeflow-tools/notebooks/notebook-controller/kustomization.yaml line 32 is referrring to jupyterWebApp tag instead of notebookController tag
```

**Comment by thesuperzapper** [comment]
@kotari can you please give a little more context?

Is this an error?

How do you reproduce it?

**Comment by kotari** [comment]
I was  overriding repos in sample_values.yaml by using my private repo and tags
notebooks.images.jupyterWebApp.tag = <<my jupyter web app tag>>
notebooks.images.notebookController.tag = <<my notebook controller tag>>

and when I run 
```
notebooks:
    enabled: true
    ## image overrides
    ##
    images:
      jupyterWebApp:
        repository: << jupyter web app repo >>
        tag: << jupyter web app tag >>
      notebookController:
        repository: << notebook controller repo >>
        tag: << notebook controller tag>>
deploykf generate --source-version=0.1.5 --values sample-values.yaml --output-dir ./GENERATOR_OUTPUT
```
notebook controller tag comes out as << notebook controller repo >>:<< jupyter web app tag >> instead of << notebook controller repo >>:<< notebook controller tag>>
