### ISSUE TITLE
dkf-core--deploykf-istio-gateway failed to create load balancer services in EKS cluster 

### ISSUE THREAD

**Issue by tppalani** [deployKF/deployKF#200]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

v0.1.5

### Kubernetes Distribution

EKS

### Kubernetes Version

```shell
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.11-eks-db838b0
```

### Description

When i'm Syncing dkf-core--deploykf-istio-gateway, i can see deploykf-gateway service getting failed with below error, do we need keep the service type as load balancer as mandatory ? 

### Relevant Logs

```shell
*Failed build model due to UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::123456789:assumed-role/mycluster-alb-role/635457896531455782559875 is not authorized to perform: ec2:CreateSecurityGroup on resource: arn:aws:ec2:us-east-2:123456789:vpc/vpc-03b408c5330c3936d with an explicit deny in a permissions boundary. Encoded authorization failure message: *
```

### deployKF Values (Optional)

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploykf-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: deploykf-gateway
    app.kubernetes.io/version: 1.17.8
    argocd.argoproj.io/instance: dkf-core--deploykf-istio-gateway
    helm.sh/chart: gateway-1.17.8
    istio: deploykf-gateway
  name: deploykf-gateway
  namespace: deploykf-istio-gateway
spec:
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: deploykf-gateway
    istio: deploykf-gateway
  type: LoadBalancer

```
```
