### ISSUE TITLE
Quick start installation   guide failed 

### ISSUE THREAD

**Issue by tppalani** [deployKF/deployKF#202]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

v0.1.5

### Kubernetes Distribution

kind

### Kubernetes Version

```shell
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```

### Description

According to the latest guide https://www.deploykf.org/guides/local-quickstart/ i have follwed the instraction but when i'm trying to create argocd application using below yaml file i'm below error.

```


$ git branch
* main

# clone the deploykf repo
# NOTE: we use 'main', as the latest plugin version always lives there
git clone -b main https://github.com/deployKF/deployKF.git ./deploykf

# ensure the script is executable
chmod +x ./deploykf/argocd-plugin/install_argocd.sh

# run the install script
# WARNING: this will install into your current kubectl context
bash ./deploykf/argocd-plugin/install_argocd.sh
```

```
$ kubectl get --namespace argocd pods
NAME                                                READY   STATUS    RESTARTS   AGE
argocd-application-controller-0                     1/1     Running   0          2m27s
argocd-applicationset-controller-79b7777965-s8cqd   1/1     Running   0          2m28s
argocd-dex-server-7c4c796bf8-2g5t5                  1/1     Running   0          2m28s
argocd-notifications-controller-6cb8857cb9-sbw2x    1/1     Running   0          2m28s
argocd-redis-6c99d949c5-jq6pv                       1/1     Running   0          2m28s
argocd-repo-server-7d894969c6-59dlt                 2/2     Running   0          2m27s
argocd-server-56bf96f47d-t59md                      1/1     Running   0          2m27s
```

### Relevant Logs

```shell
Unable to create application: application spec for deploykf-app-of-apps is invalid: InvalidSpecError: Unable to generate manifests in .: rpc error: code = Unknown desc = plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `/bin/bash -c "set -eo pipefail\n\n## ensure exactly one of 'source_version' or 'source_path' was provided\nif [[ -n \"$PARAM_SOURCE_VERSION\" && -n \"$PARAM_SOURCE_PATH\" ]]; then\n echo \"ERROR: both 'source_version' and 'source_path' were set, but we require exactly one\" >&2\n exit 1\nelif [[ -z \"$PARAM_SOURCE_VERSION\" && -z \"$PARAM_SOURCE_PATH\" ]]; then\n echo \"ERROR: neither of 'source_version' of 'source_path' were set, but we require exactly one\" >&2\n exit 1\nfi\n\n## ensure exactly one of 'output_kustomize_path' or 'output_helm_path' was provided\nif [[ -n \"$PARAM_OUTPUT_KUSTOMIZE_PATH\" && -n \"$PARAM_OUTPUT_HELM_PATH\" ]]; then\n echo \"ERROR: both 'output_kustomize_path' and 'output_helm_path' were set, but we require exactly one\" >&2\n exit 1\nfi\n\n## if no paths are set, default to the argocd app-of-apps\nif [[ -z \"$PARAM_OUTPUT_KUSTOMIZE_PATH\" && -z \"$PARAM_OUTPUT_HELM_PATH\" ]]; then\n PARAM_OUTPUT_KUSTOMIZE_PATH=\"./argocd/\"\nfi\n\nDKF_ARGS=()\n\n## set 'deploykf --output-dir' argument\nOUTPUT_DIR=\"./__PLUGIN_GENERATOR_OUTPUT__\"\nDKF_ARGS+=(\"--output-dir\" \"$OUTPUT_DIR\")\n\n## set 'deploykf --source-version' argument\nif [[ -n \"$PARAM_SOURCE_VERSION\" ]]; then\n DKF_ARGS+=(\"--source-version\" \"$PARAM_SOURCE_VERSION\")\nfi\n\n## set 'deploykf --source-path' argument\nif [[ -n \"$PARAM_SOURCE_PATH\" ]]; then\n DKF_ARGS+=(\"--source-path\" \"$PARAM_SOURCE_PATH\")\nfi\n\n## set 'deploykf --values' argument for each 'values_files' path\nfor env_var in ${!PARAM_VALUES_FILES_@}\ndo\n VALUES_FILE_PATH=\"${!env_var}\"\n if [[ ! -f \"$VALUES_FILE_PATH\" ]]; then\n echo \"ERROR: the provided values file '$VALUES_FILE_PATH' does not exist\" >&2\n exit 1\n fi\n DKF_ARGS+=(\"--values\" \"$VALUES_FILE_PATH\")\ndone\n\n## set 'deploykf --values' argument for the provided 'values' string\nif [[ -n \"$PARAM_VALUES\" ]]; then\n USER_VALUES_FILE_PATH=\"./__PLUGIN_USER_VALUES__.yaml\"\n echo \"$PARAM_VALUES\" > \"$USER_VALUES_FILE_PATH\"\n DKF_ARGS+=(\"--values\" \"$USER_VALUES_FILE_PATH\")\nfi\n\n## set 'deploykf --values' argument for values required by the plugin\nREQUIRED_VALUES='{\"argocd\":{\"source\":{\"plugin\":{\"enabled\":true}}}}'\nREQUIRED_VALUES_FILE_PATH=\"./__PLUGIN_REQUIRED_VALUES__.yaml\"\necho \"$REQUIRED_VALUES\" > \"$REQUIRED_VALUES_FILE_PATH\"\nDKF_ARGS+=(\"--values\" \"$REQUIRED_VALUES_FILE_PATH\")\n\n## run the deploykf generator\ndeploykf generate \"${DKF_ARGS[@]}\"\n\n## ensure the provided 'output_kustomize_path' exists\nif [[ -n \"$PARAM_OUTPUT_KUSTOMIZE_PATH\" ]]; then\n OUTPUT_KUSTOMIZE_PATH=$(realpath \"$OUTPUT_DIR/$PARAM_OUTPUT_KUSTOMIZE_PATH\")\n if [[ ! -d \"$OUTPUT_KUSTOMIZE_PATH\" ]]; then\n echo \"ERROR: the provided 'output_kustomize_path' '$OUTPUT_KUSTOMIZE_PATH' does not exist\" >&2\n exit 1\n fi\nfi\n\n## ensure the provided 'output_helm_path' exists\nif [[ -n \"$PARAM_OUTPUT_HELM_PATH\" ]]; then\n OUTPUT_HELM_PATH=$(realpath \"$OUTPUT_DIR/$PARAM_OUTPUT_HELM_PATH\")\n if [[ ! -d \"$OUTPUT_HELM_PATH\" ]]; then\n echo \"ERROR: the provided 'output_helm_path' '$OUTPUT_HELM_PATH' does not exist\" >&2\n exit 1\n fi\n\n ## add the helm repos for the chart dependencies\n helm dependency list --max-col-width 10000 \"$OUTPUT_HELM_PATH\" | awk 'NR>1 {print $1,$3}' | while read -r name url; do\n if [[ -n \"$name\" && -n \"$url\" && \"$url\" =~ \"^https?://\" ]]; then\n helm repo add \"$name\" \"$url\" --force-update\n fi\n done\n\n ## pull the helm chart dependencies\n helm dependency build \"$OUTPUT_HELM_PATH\"\nfi\n"` failed exit status 1: Error: Get "https://objects.githubusercontent.com/github-production-release-asset-2e65be/614078982/6fd87e76-59f1-4ccf-aa0a-6e18de122dcd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240827%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240827T023958Z&X-Amz-Expires=300&X-Amz-Signature=488b399902e42207f7b89b815065c66c96993853260943d595a37fe98b52d297&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=614078982&response-content-disposition=attachment%3B%20filename%3Ddeploykf-0.1.5-generator.zip&response-content-type=application%2Foctet-stream": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
```


### deployKF Values (Optional)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploykf-app-of-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: deploykf-app-of-apps
    app.kubernetes.io/part-of: deploykf
spec:
  project: "default"
  source:
    ## source git repo configuration
    ##  - we use the 'deploykf/deploykf' repo so we can read its 'sample-values.yaml'
    ##    file, but you may use any repo (even one with no files)
    ##
    repoURL: "https://github.com/deployKF/deployKF.git"
    targetRevision: "v0.1.5"
    path: "."

    ## plugin configuration
    ##
    plugin:
      name: "deploykf"
      parameters:

        ## the deployKF generator version
        ##  - available versions: https://github.com/deployKF/deployKF/releases
        ##
        - name: "source_version"
          string: "0.1.5"

        ## paths to values files within the `repoURL` repository
        ##  - the values in these files are merged, with later files taking precedence
        ##  - we strongly recommend using 'sample-values.yaml' as the base of your values
        ##    so you can easily upgrade to newer versions of deployKF
        ##
        - name: "values_files"
          array:
            - "./sample-values.yaml"

        ## a string containing the contents of a values file
        ##  - this parameter allows defining values without needing to create a file in the repo
        ##  - these values are merged with higher precedence than those defined in `values_files`
        ##
        - name: "values"
          string: |
            ##
            ## This demonstrates how you might structure overrides for the 'sample-values.yaml' file.
            ## For a more comprehensive example, see the 'sample-values-overrides.yaml' in the main repo.
            ##
            ## Notes:
            ##  - YAML maps are RECURSIVELY merged across values files
            ##  - YAML lists are REPLACED in their entirety across values files
            ##  - Do NOT include empty/null sections, as this will remove ALL values from that section.
            ##    To include a section without overriding any values, set it to an empty map: `{}`
            ##

            ## --------------------------------------------------------------------------------
            ##                                      argocd
            ## --------------------------------------------------------------------------------
            argocd:
              namespace: argocd
              project: default

            ## --------------------------------------------------------------------------------
            ##                                    kubernetes
            ## --------------------------------------------------------------------------------
            kubernetes:
              {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

            ## --------------------------------------------------------------------------------
            ##                              deploykf-dependencies
            ## --------------------------------------------------------------------------------
            deploykf_dependencies:

              ## --------------------------------------
              ##             cert-manager
              ## --------------------------------------
              cert_manager:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

              ## --------------------------------------
              ##                 istio
              ## --------------------------------------
              istio:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

              ## --------------------------------------
              ##                kyverno
              ## --------------------------------------
              kyverno:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

            ## --------------------------------------------------------------------------------
            ##                                  deploykf-core
            ## --------------------------------------------------------------------------------
            deploykf_core:

              ## --------------------------------------
              ##             deploykf-auth
              ## --------------------------------------
              deploykf_auth:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

              ## --------------------------------------
              ##        deploykf-istio-gateway
              ## --------------------------------------
              deploykf_istio_gateway:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

              ## --------------------------------------
              ##      deploykf-profiles-generator
              ## --------------------------------------
              deploykf_profiles_generator:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

            ## --------------------------------------------------------------------------------
            ##                                   deploykf-opt
            ## --------------------------------------------------------------------------------
            deploykf_opt:

              ## --------------------------------------
              ##            deploykf-minio
              ## --------------------------------------
              deploykf_minio:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

              ## --------------------------------------
              ##            deploykf-mysql
              ## --------------------------------------
              deploykf_mysql:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

            ## --------------------------------------------------------------------------------
            ##                                  kubeflow-tools
            ## --------------------------------------------------------------------------------
            kubeflow_tools:

              ## --------------------------------------
              ##                 katib
              ## --------------------------------------
              katib:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

              ## --------------------------------------
              ##               notebooks
              ## --------------------------------------
              notebooks:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

              ## --------------------------------------
              ##               pipelines
              ## --------------------------------------
              pipelines:
                {} # <-- REMOVE THIS, IF YOU INCLUDE VALUES UNDER THIS SECTION!

  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"
```
