### ISSUE TITLE
Nginx kubernetes deploykf-gateway loadbalancer service

### ISSUE THREAD

**Issue by tppalani** [deployKF/deployKF#212]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

v0.1.5

### Kubernetes Distribution

EKS

### Kubernetes Version

```shell
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

### Description

According https://www.deploykf.org/guides/platform/deploykf-gateway/#use-a-loadbalancer-service i'm trying to configure the nginx ingress to expose the traffic to from the browser instead of port forwarding.

when i have tried with port forwarding from my local widows VM i can able to access the website according to my custom domain name. But when i'm doing from DNS name i'm not able to access it from browser.

port forward test

```

kubectl port-forward \
  --namespace "deploykf-istio-gateway" \
  svc/deploykf-gateway 8080:http 8443:https

Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
Forwarding from 127.0.0.1:8443 -> 8443
Forwarding from [::1]:8443 -> 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443
```
able to access from the browser 

https://kubeflow.com:8443/

### Relevant Logs

```shell
NA
```

### deployKF Values (Optional)

```yaml
## --------------------------------------
  ##        deploykf-istio-gateway
  ## --------------------------------------
  deploykf_istio_gateway:
    namespace: deploykf-istio-gateway
    

    ## extra manifests
    ##  - a list of strings containing extra Kubernetes resource manifests
    ##  - strings can include deployKF templates `{{< ... >}}` and Helm templates `{{ ... }}`
    ##
    extraManifests:
      - |
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: deploykf-gateway
          annotations:
            nginx.ingress.kuberenets.io/server-alias: "deploykf-dashboard.com"
            nginx.ingress.kubernetes.io/backend-protocol: "http"
            nginx.ingress.kubernetes.io/proxy-ssl-name: "kubeflow.com"
            nginx.ingress.kubernetes.io/proxy-ssl-server-name: "on"
            nginx.ingress.kubernetes.io/proxy-ssl-secret: "deploykf-istio-gateway/deploykf-istio-gateway-cert"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
        spec:
          ingressClassName: nginx
          tls:
            - secretName: "deploykf-istio-gateway-cert"  
          rules:
            - host: "kubeflow.com"
              http:
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: deploykf-gateway
                        port:
                          name: https
            - host: "*.kubeflow.com"
              http:
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: deploykf-gateway
                        port:
                          name: https

    ## istio gateway configs
    ##
    gateway:

      ## the hostname that the gateway will listen on
      ##  - subdomains of this hostname may also be used, depending on which apps are enabled
      ##
      hostname: kubeflow.com

      ## the ports that the gateway will listen on
      ##  - these are the "internal" ports which the gateway use, and can be different
      ##    to the user-facing ports which the service listens on, see `gatewayService.ports`
      ##
      ports:
        http: 80
        https: 443
      # tls:
      #   matchSNI: false
      #   redirect: true

      ## the pod labels used by the gateway to find the ingress gateway deployment
      ##
      selectorLabels:
        app: deploykf-gateway
        istio: deploykf-gateway

    ## istio gateway deployment configs
    ##
    gatewayDeployment:
      serviceAccount:
        name: deploykf-gateway
        annotations: {}

    ## istio gateway service configs
    ##
    gatewayService:
      name: deploykf-gateway
      annotations: {}
      type: ClusterIP
```
