### ISSUE TITLE
kubeflow dashboard not able to list the namespaces

### ISSUE THREAD

**Issue by tppalani** [deployKF/deployKF#215]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

v0.1.5

### Kubernetes Distribution

EKS

### Kubernetes Version

```shell
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.8-eks-a737599
```

### Description

Thanks Mr.Mathew Wicks and team for wonderful document and steps which written in quick startup page. Documentation and steps are more clear and details description for new learners who willing to learn MLOPS.

I have configured deployKF setup in my new EKS cluster and i configured apps of apps using GitOps method to make application healthy and up to date.

Now i'm in final stage to configure profile management section, and i have few issues in it, when i'm accessing my kuebflow dashboard under the select namespace dropdown I'm not able to list any namespace which is availbile inside the EKS cluster.

I will try to explain the sample values how i configured it.

1. I have AD group name called KF-ADMIN.
2. I'm the part of the above group and username is (user1)
3. when i'm trying to login to kubeflow dashboard i'm using username and password combination of ( AD group username and password)
4.  Here is the profile generator values.yaml configuration.

![image](https://github.com/user-attachments/assets/9450590b-a529-42ad-924a-1b6de1775d0c)

can you please help me on this.

### Relevant Logs

```shell
NA
```

### deployKF Values (Optional)

```yaml
## --------------------------------------
  ##      deploykf-profiles-generator
  ## --------------------------------------
  deploykf_profiles_generator:

    profileDefaults:
      
      profileNamePrefix: ""

      memberAccess:
        role: view
        notebooksAccess: false

      plugins: []
      resourceQuotaSpec: {}
      tools:
        kubeflowPipelines:
          objectStoreAuth:
            existingSecret: "kubeflow-pipelines--profile-object-store-auth--{profile_name}"
            existingSecretNamespace: ""
            existingSecretAccessKeyKey: "access_key"
            existingSecretSecretKeyKey: "secret_key"

    users:
     - id: viswa
       email: "viswa.t@company.com"
     
    groups:
     - id: KF-ADMIN
       users:
         - viswa
    profiles:
     - name: kf-admin
       members:
        - group: KF-ADMIN
          access:
            role: edit
            notebooksAccess: true
```

**Comment by thesuperzapper** [comment]
@tppalani I think you are slightly misunderstanding how the `groups` value works, it currently does not read the groups from your identity provider, you need to specify the list of users who are in it:

https://www.deploykf.org/guides/platform/deploykf-profiles/#group-entities

**Comment by harsha1163** [comment]
I am also facing the same issue when we have Azure Entra as a login mechanism. Sometimes we are not able to get the namespace dropdown when logged into the deploykf dashboard.

**Comment by tppalani** [comment]
Hi @thesuperzapper 

thanks for the quick notes. As you requested i have added list of users which is part of the AD groups but still i'm not able to see any namespaces from kubeflow dashboard, do you have any other way how to troubleshoot to identify  where its blocking.

Here the update code snippet.

```
## --------------------------------------
  ##      deploykf-profiles-generator
  ## --------------------------------------
  deploykf_profiles_generator:

    ## profile defaults
    ##
    profileDefaults:  
      profileNamePrefix: ""
      memberAccess:
        role: view
        notebooksAccess: false
      plugins: []
      resourceQuotaSpec: {}

      tools:

        kubeflowPipelines:
          objectStoreAuth:
            existingSecret: "kubeflow-pipelines--profile-object-store-auth--{profile_name}"
            existingSecretNamespace: ""
            existingSecretAccessKeyKey: "access_key"
            existingSecretSecretKeyKey: "secret_key"

    users:
     - id: user-1
       email: "user-1@email.com"

    groups:
      - id: KF-ADMIN
        users:
          - user-1
    profiles:
     - name: team-1
       members:
        - group: KF-ADMIN
          access:
            role: edit
            notebooksAccess: true
```

can you please help me.

**Comment by tppalani** [comment]
Adding one more note when i have see argocd UI dkf-core--deploykf-profiles-generator app i can see new profile is created automatically based on the values.yaml with below yaml content, can you validate because i can  see admin@example.com not sure from where its coming.

```
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"kubeflow.org/v1","kind":"Profile","metadata":{"annotations":{"argocd.argoproj.io/sync-wave":"-10"},"labels":{"app.kubernetes.io/instance":"dkf-core--deploykf-profiles-generator","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"deploykf-profiles-generator","argocd.argoproj.io/instance":"dkf-core--deploykf-profiles-generator","helm.sh/chart":"deploykf-profiles-generator-1.0.0"},"name":"team-1"},"spec":{"owner":{"kind":"User","name":"admin@example.com"},"resourceQuotaSpec":{}}}
  creationTimestamp: '2024-10-15T11:34:40Z'
  finalizers:
    - profile-finalizer
  generation: 1
  labels:
    app.kubernetes.io/instance: dkf-core--deploykf-profiles-generator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: deploykf-profiles-generator
    argocd.argoproj.io/instance: dkf-core--deploykf-profiles-generator
    helm.sh/chart: deploykf-profiles-generator-1.0.0
  name: team-1
  resourceVersion: '45901151'
  uid: 461feeef-6555-492b-b452-6d79c980b86d
spec:
  owner:
    kind: User
    name: admin@example.com
  resourceQuotaSpec: {}

```

**Comment by thesuperzapper** [comment]
@tppalani the `admin@example.com` is the owner of all profiles by default (there is a value, but don't change it). 

I recommend `admin@example.com` as the default owner because each profile needs to have an owner (and the owner can't be changed). To make this secure, ensure you disable login for `admin@example.com`, because end users should only have editor access, not owner.

**Comment by thesuperzapper** [comment]
@tppalani @harsha1163 Please ensure a few things:

1. That the email has the same capitalization as what is being sent from AD 
     - _(there is a value to cast them to lowercase, but only use this if your AD sends random capitalization because it introduces a slight security risk)_
3. Ensure you have run the full sync script (not only the profiles generator app).

For reference, here is the value to cast all emails to lowercase (only use as a last resort):

```yaml
deploykf_core:
  deploykf_istio_gateway:
    gateway:

      ## if the email passed in `X-Auth-Request-Email` by `oauth2-proxy` is cast to lowercase
      ##  - note, this will only affect the email passed to Kubeflow apps, other apps connected to
      ##    dex OIDC will still receive the original email, so it's usually best to standardize
      ##    the emails in your upstream identity system
      ##  - this may be helpful if your identity system returns emails with uppercase letters and you
      ##    want to standardize on lowercase emails for RoleBindings
      ##  - this value will also affect the profiles generated by `deploykf-profiles-generator`
      ##
      emailToLowercase: true
```

**Comment by tppalani** [comment]
Thanks for the help. i have added email configuration and i have done full sync using argocd Ui

```
 ## istio gateway configs
    ##
    gateway:
      emailToLowercase: true
```

but still i don't see any namespace listed in kubeflow dashboard

**Comment by thesuperzapper** [comment]
@tppalani have you tried logging out and in again? (Also try deleting cookies for your deployKF site, by clicking under the lock icon beside the URL on Chrome).

__If that does not work, do the following:__

1. Check that you are seeing the expected email in the logs of the `dex` and `oauth2-proxy` pods (in the `deploykf-auth` namespace) when logging in. For example, these logs from `dex` show `user1@example.com` under the `email=` field:

    ```
    time="2024-10-15T18:06:20Z" level=info msg="login successful: connector \"local\",username=\"user1@example.com\", preferred_username=\"\", email=\"user1@example.com\", groups=[]"
    ```
2. Ensure that there is a `RoleBinding` in the `team-1` Namespace called something like `user-user1-example-com-clusterrole-edit`, and that it has the correct email.

**Comment by tppalani** [comment]
Hi @thesuperzapper 

here the pod logs i can see successful authentication 

```
time="2024-10-15T17:38:39Z" level=info msg="listening (http) on 0.0.0.0:5556"
time="2024-10-15T17:42:04Z" level=info msg="login successful: connector \"okta\", username=\"Admin Account - T, palanisamy\", preferred_username=\"AN123456AD@dev.point.com\", email=\"AN123456AD@dev.point.com\", groups=[]"


10.188.213.173 - a4b071fa-75c9-4ef0-9bb6-c341f050e16e - AN123456AD@dev.point.com [2024/10/15 18:12:28] eks.com GET static://200 "/jupyter/static/roboto-latin-normal400.465390c6e54c60f4a15f.woff2" HTTP/1.1 "" 200 13 0.000
10.188.213.173 - fd6c002d-5324-45e6-b362-d249d088b816 - AN123456AD@dev.point.com [2024/10/15 18:12:29] eks.com GET static://200 "/jupyter/static/roboto-latin-normal500.324b1e6d0f5ae7c6ab42.woff2" HTTP/1.1 "" 200 13 0.000
```

**Comment by thesuperzapper** [comment]
@tppalani and you can see a `RoleBinding` in the `team-1` namespace with the exact same email (but in lowercase)?

The email should be in the `subjects[].name` and `metadata.annotations.user` like this:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    role: edit

    ## \/ this will be the email \/
    user: user1@example.com
 
  ## \/ this will be different, for the email \/
  name: user-user1-example-com-clusterrole-edit

  namespace: team-1

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User

  ## \/ this will be the email \/
  name: user1@example.com
```

**Comment by tppalani** [comment]
Hi @thesuperzapper 

As you requested i have revisited my sample values.yaml file and i have re-configured as like below.

```
users:
     - id: AN123456AD
       email: "AN123456AD@dev.point.com"
groups:
      - id: CAAS-KF-ADMIN
        users:
          - AN123456AD
profiles:

     - name: caas-admin
       members:
        - group: CAAS-KF-ADMIN
          access:
            role: edit
            notebooksAccess: true
``` 

Note: i have added emailToLowercase: true as well as you mentioned earlier note. post this i have synced all the apps using argocd UI page, then finally i cleared cookies from the browser then, then, then, finally i can see namespace caas-admin in the kubeflow dashboard 💯 

Next few validation from caas-admin namespace rolebinding

1. first rb user-an123456ad-dev-point-com-clusterrole-edit, if you subject user name coming as a upper case only (AN123456AD@dev-point.com) is this expected one ?

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-an123456ad-dev-point-com-clusterrole-edit
  namespace: caas-admin
  labels:
    app.kubernetes.io/instance: dkf-core--deploykf-profiles-generator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: deploykf-profiles-generator
    argocd.argoproj.io/instance: dkf-core--deploykf-profiles-generator
    helm.sh/chart: deploykf-profiles-generator-1.0.0
  annotations:
    role: edit
    user: AN123456AD@dev-point.com
  subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: AN123456AD@dev-point.com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-edit

```

if this is expectation behavior then we are good to close this ticket.
