### ISSUE TITLE
Pipelines API server crashes on SQL connection cleaner goroutine

### ISSUE THREAD

**Issue by Liana64** [deployKF/deployKF#219]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.5

### Kubernetes Distribution

v1.31.1

### Kubernetes Version

```shell
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.31.1
====================================
K8s: v1.31.1
Talos: v1.8.0
Go version: go1.22.7
Cilium: 1.16.2
mysql --version: mysql  Ver 8.0.40 for Linux on x86_64 (MySQL Community Server - GPL)
```

### Description

I'm running into some trouble with getting Pipelines running on Talos. I would greatly appreciate help with this is as it is for non-profit medical research.

### Steps to reproduce

Deploy deployKF on Talos 1.8.0, with MinIO running locally on the cluster and with an external MySQL server

### Expected result

Kubeflow pipelines initializes and connects to a MySQL server. Kubeflow persistence agent does not crash.

### Materials and Reference

- Everything syncs fine with ArgoCD except for the pipelines component 
- CiliumIdentity resources are excluded from Kyverno
- inotify limits are set:

```
---
machine:
  sysctls:
    fs.inotify.max_user_instances: "1280"
    fs.inotify.max_user_watches: "655360"
```

- Changing resource request limits for the pods does not affect the error
- The database is accessible remotely and the process list shows connection:

```
mysql> SHOW FULL PROCESSLIST;
+----+----------+-------------+---------------+---------+------+-------+-----------------------+
| Id | User     | Host        | db            | Command | Time | State | Info                  |
+----+----------+-------------+---------------+---------+------+-------+-----------------------+
|  8 | kubeflow | arc1:39022  | katib         | Sleep   |   46 |       | NULL                  |
| 86 | kubeflow | liana:56074 | NULL          | Query   |    0 | init  | SHOW FULL PROCESSLIST |
| 91 | kubeflow | arc1:45090  | kfp_pipelines | Sleep   |    0 |       | NULL                  |
+----+----------+-------------+---------------+---------+------+-------+-----------------------+
3 rows in set, 1 warning (0.00 sec)
```

---

Impacted by this bug? Give it a 👍. 

### Relevant Logs

```shell
Previous Logs(kubeflow/ml-pipeline-persistenceagent-5788c7d84-fr96l:ml-pipeline-persistenceagent)

│ ml-pipeline-persistenceagent W1021 22:00:12.070284       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inCluster │
│ Config.  This might not work.                                                                                                                          │
│ ml-pipeline-persistenceagent time="2024-10-21T22:02:20Z" level=fatal msg="Error creating ML pipeline API Server client: Failed to initialize pipeline  │
│ client. Error: Waiting for ml pipeline API server failed after all attempts.: Get \"http://ml-pipeline:8888/apis/v1beta1/healthz\": dial tcp 10.97.186 │
│ .98:8888: connect: operation not permitted: Waiting for ml pipeline API server failed after all attempts.: Get \"http://ml-pipeline:8888/apis/v1beta1/ │
│ healthz\": dial tcp 10.97.186.98:8888: connect: operation not permitted"                                                                               │
│ Stream closed EOF for kubeflow/ml-pipeline-persistenceagent-6667f7df-b2gnl (ml-pipeline-persistenceagent)


Previous Logs(kubeflow/ml-pipeline-69cc878cfb-tjfng:ml-pipeline-api-server)

│ goroutine 177 [IO wait]:                                                                                                                               │
│ runtime.gopark(0x0?, 0xb?, 0x0?, 0x0?, 0x6?)                                                                                                           │
│     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000d9fcc8 sp=0xc000d9fca8 pc=0x444016                                                            │
│ runtime.netpollblock(0x489e45?, 0x40c04f?, 0x0?)                                                                                                       │
│     /usr/local/go/src/runtime/netpoll.go:527 +0xf7 fp=0xc000d9fd00 sp=0xc000d9fcc8 pc=0x43c977                                                         │
│ internal/poll.runtime_pollWait(0x7f7409a46a48, 0x72)                                                                                                   │
│     /usr/local/go/src/runtime/netpoll.go:306 +0x89 fp=0xc000d9fd20 sp=0xc000d9fd00 pc=0x46f1a9                                                         │
│ internal/poll.(*pollDesc).wait(0xc000908600?, 0xc000d9fed0?, 0x1)                                                                                      │
│     /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc000d9fd48 sp=0xc000d9fd20 pc=0x4f0592                                            │
│ internal/poll.(*pollDesc).waitRead(...)                                                                                                                │
│     /usr/local/go/src/internal/poll/fd_poll_runtime.go:89                                                                                              │
│ internal/poll.(*FD).Read(0xc000908600, {0xc000d9fed0, 0x10000, 0x10000})                                                                               │
│     /usr/local/go/src/internal/poll/fd_unix.go:167 +0x299 fp=0xc000d9fde0 sp=0xc000d9fd48 pc=0x4f1979                                                  │
│ os.(*File).read(...)                                                                                                                                   │
│     /usr/local/go/src/os/file_posix.go:31                                                                                                              │
│ os.(*File).Read(0xc0007aa010, {0xc000d9fed0?, 0x0?, 0x0?})                                                                                             │
│     /usr/local/go/src/os/file.go:118 +0x5e fp=0xc000d9fe38 sp=0xc000d9fde0 pc=0x4fd69e                                                                 │
│ github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc000233ef0)                                                                                       │
│     /go/pkg/mod/github.com/fsnotify/fsnotify@v1.6.0/backend_inotify.go:356 +0xdf fp=0xc000daffc8 sp=0xc000d9fe38 pc=0x18941df                          │
│ github.com/fsnotify/fsnotify.NewWatcher.func1()                                                                                                        │
│     /go/pkg/mod/github.com/fsnotify/fsnotify@v1.6.0/backend_inotify.go:150 +0x26 fp=0xc000daffe0 sp=0xc000daffc8 pc=0x1893c06                          │
│ runtime.goexit()                                                                                                                                       │
│     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000daffe8 sp=0xc000daffe0 pc=0x474ee1                                                        │
│ created by github.com/fsnotify/fsnotify.NewWatcher                                                                                                     │
│     /go/pkg/mod/github.com/fsnotify/fsnotify@v1.6.0/backend_inotify.go:150 +0x1b0                                                                      │
│                                                                                                                                                        │
│ goroutine 178 [select]:                                                                                                                                │
│ runtime.gopark(0xc0004c1fb0?, 0x2?, 0x0?, 0x0?, 0xc0004c1f34?)                                                                                         │
│     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0004c1d98 sp=0xc0004c1d78 pc=0x444016                                                            │
│ runtime.selectgo(0xc0004c1fb0, 0xc0004c1f30, 0x0?, 0x0, 0x0?, 0x1)                                                                                     │
│     /usr/local/go/src/runtime/select.go:327 +0x7be fp=0xc0004c1ed8 sp=0xc0004c1d98 pc=0x4539be                                                         │
│ github.com/spf13/viper.(*Viper).WatchConfig.func1.1()                                                                                                  │
│     /go/pkg/mod/github.com/spf13/viper@v1.10.1/viper.go:413 +0x105 fp=0xc0004c1fe0 sp=0xc0004c1ed8 pc=0x1a12025                                        │
│ runtime.goexit()                                                                                                                                       │
│     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004c1fe8 sp=0xc0004c1fe0 pc=0x474ee1                                                        │
│ created by github.com/spf13/viper.(*Viper).WatchConfig.func1                                                                                           │
│     /go/pkg/mod/github.com/spf13/viper@v1.10.1/viper.go:411 +0x2d1                                                                                     │
│                                                                                                                                                        │
│ goroutine 192 [select]:                                                                                                                                │
│ runtime.gopark(0xc0004c4780?, 0x2?, 0x0?, 0x0?, 0xc0004c4740?)                                                                                         │
│     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0004c45c0 sp=0xc0004c45a0 pc=0x444016                                                            │
│ runtime.selectgo(0xc0004c4780, 0xc0004c473c, 0x0?, 0x0, 0x0?, 0x1)                                                                                     │
│     /usr/local/go/src/runtime/select.go:327 +0x7be fp=0xc0004c4700 sp=0xc0004c45c0 pc=0x4539be                                                         │
│ github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1()                                                                                       │
│     /go/pkg/mod/github.com/go-sql-driver/mysql@v1.6.0/connection.go:614 +0xaa fp=0xc0004c47e0 sp=0xc0004c4700 pc=0x18d93ca                             │
│ runtime.goexit()                                                                                                                                       │
│     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004c47e8 sp=0xc0004c47e0 pc=0x474ee1                                                        │
│ created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher                                                                                    │
│     /go/pkg/mod/github.com/go-sql-driver/mysql@v1.6.0/connection.go:611 +0x10a                                                                         │
│                                                                                                                                                        │
│ goroutine 161 [select]:                                                                                                                                │
│ runtime.gopark(0xc000577788?, 0x2?, 0x8a?, 0x62?, 0xc000577784?)                                                                                       │
│     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000577610 sp=0xc0005775f0 pc=0x444016                                                            │
│ runtime.selectgo(0xc000577788, 0xc000577780, 0x0?, 0x0, 0x0?, 0x1)                                                                                     │
│     /usr/local/go/src/runtime/select.go:327 +0x7be fp=0xc000577750 sp=0xc000577610 pc=0x4539be                                                         │
│ database/sql.(*DB).connectionOpener(0xc0005584e0, {0x2b72ca0, 0xc000496f50})                                                                           │
│     /usr/local/go/src/database/sql/sql.go:1218 +0x8d fp=0xc0005777b8 sp=0xc000577750 pc=0x184bb6d                                                      │
│ database/sql.OpenDB.func1()                                                                                                                            │
│     /usr/local/go/src/database/sql/sql.go:791 +0x2e fp=0xc0005777e0 sp=0xc0005777b8 pc=0x1849eee                                                       │
│ runtime.goexit()                                                                                                                                       │
│     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005777e8 sp=0xc0005777e0 pc=0x474ee1                                                        │
│ created by database/sql.OpenDB                                                                                                                         │
│     /usr/local/go/src/database/sql/sql.go:791 +0x18d                                                                                                   │
│                                                                                                                                                        │
│ goroutine 141 [select]:                                                                                                                                │
│ runtime.gopark(0xc0004c3f90?, 0x2?, 0x0?, 0x0?, 0xc0004c3f74?)                                                                                         │
│     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0004c3de8 sp=0xc0004c3dc8 pc=0x444016                                                            │
│ runtime.selectgo(0xc0004c3f90, 0xc0004c3f70, 0x0?, 0x0, 0x0?, 0x1)                                                                                     │
│     /usr/local/go/src/runtime/select.go:327 +0x7be fp=0xc0004c3f28 sp=0xc0004c3de8 pc=0x4539be                                                         │
│ database/sql.(*DB).connectionCleaner(0xc0005584e0, 0x1?)                                                                                               │
│     /usr/local/go/src/database/sql/sql.go:1061 +0xa7 fp=0xc0004c3fc0 sp=0xc0004c3f28 pc=0x184b007                                                      │
│ database/sql.(*DB).startCleanerLocked.func1()                                                                                                          │
│     /usr/local/go/src/database/sql/sql.go:1048 +0x2a fp=0xc0004c3fe0 sp=0xc0004c3fc0 pc=0x184af2a                                                      │
│ runtime.goexit()                                                                                                                                       │
│     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004c3fe8 sp=0xc0004c3fe0 pc=0x474ee1                                                        │
│ created by database/sql.(*DB).startCleanerLocked                                                                                                       │
│     /usr/local/go/src/database/sql/sql.go:1048 +0x105                                                                                                  │
│                                                                                                                                                        │
│ rax    0x0                                                                                                                                             │
│ rbx    0x7                                                                                                                                             │
│ rcx    0x40b2ee                                                                                                                                        │
│ rdx    0x0                                                                                                                                             │
│ rdi    0x7                                                                                                                                             │
│ rsi    0x6                                                                                                                                             │
│ rbp    0xc000f47670                                                                                                                                    │
│ rsp    0xc000f47630                                                                                                                                    │
│ r8     0x0                                                                                                                                             │
│ r9     0x0                                                                                                                                             │
│ r10    0x0                                                                                                                                             │
│ r11    0x202                                                                                                                                           │
│ r12    0xc000f476d0                                                                                                                                    │
│ r13    0x0                                                                                                                                             │
│ r14    0xc0000061a0                                                                                                                                    │
│ r15    0x3ebc640                                                                                                                                       │
│ rip    0x40b2ee                                                                                                                                        │
│ rflags 0x202                                                                                                                                           │
│ cs     0x33                                                                                                                                            │
│ fs     0x0                                                                                                                                             │
│ gs     0x0                                                                                                                                             │
│ Stream closed EOF for kubeflow/ml-pipeline-84d9557-jq8t2 (ml-pipeline-api-server)
```

### deployKF Values (Optional)

```yaml
---------------------------------------------mysql.cnf----------------------------------------
[mysqld]

# Defaults
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
datadir         = /var/lib/mysql
log-error       = /var/log/mysql/error.log

# Kubeflow Pipelines
disable_log_bin
default_authentication_plugin = mysql_native_password
log_error_suppression_list='MY-013360'

# Connections
max_connections = 500

# InnoDB
innodb_buffer_pool_size = 2G
innodb_file_per_table = 1

# Performance
performance_schema = ON

# Network
max_allowed_packet = 64M

# Timeouts
wait_timeout = 600
interactive_timeout = 600
connect_timeout = 30

-------------------------------------deployKF values.yaml-------------------------------------

# See:
# https://www.deploykf.org/reference/deploykf-values/
# https://github.com/deployKF/deployKF/blob/v0.1.5/generator/default_values.yaml

argocd:
  ## a prefix to use for argocd application names
  ##  - allows a single instance of argocd to manage deployKF across multiple clusters
  ##  - if non-empty, `argocd.destination` must be a remote cluster, this is because
  ##    a single cluster can only have one instance of deployKF
  ##
  appNamePrefix: ""
  namespace: argocd
  project: default
  source:
    repo:
      ## the URL of your manifest git repo
      ##  - for example, if you are using a GitHub repo named 'deployKF/examples', you might set this value
      ##    to "https://github.com/deployKF/examples" or "git@github.com:deployKF/examples.git"
      ##
      url: "<Redacted>"

      ## the git revision which contains your generated manifests
      ##  - for example, if you are using the 'main' branch of your repo, you might set this value to "main"
      ##
      revision: "main"

      ## the path within your repo where the generated manifests are stored
      ##  - for example, if you are using a folder named 'GENERATOR_OUTPUT' at the root of your repo,
      ##    you might set this value to "./GENERATOR_OUTPUT/"
      ##
      path: "./kubernetes/apps/deploykf/manifests/"
  destination:
    server: https://kubernetes.default.svc
    name: ""
deploykf_dependencies:
  cert_manager:
    enabled: false
    namespace: cert-manager
    extraManifests: []
    clusterIssuer:
      enabled: false
      issuerName: letsencrypt-prod
  istio:
    enabled: true
    namespace: istio-system
  kyverno:
    enabled: true
    namespace: kyverno
    admissionController:
      replicas: 5
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 128Mi
deploykf_core:
  deploykf_auth:
    namespace: deploykf-auth
    dex:
      staticPasswords:
        - email: "<Redacted>"
          password:
            existingSecret: "kubeflow-auth-static--<Redacted>"
            existingSecretKey: "PASSWORD_HASH"
      connectors: []
      clients:
        oauth2Proxy:
          clientId: "oauth2-proxy"
          clientSecret:
            existingSecret: "generated--dex-oauth2-proxy-client"
            existingSecretKey: "client_secret"
            generateSecret: true
        minioConsole:
          clientId: "minio-console"
          clientSecret:
            existingSecret: "generated--dex-minio-console-client"
            existingSecretKey: "client_secret"
            generateSecret: true
        argoServer:
          clientId: "argo-server"
          clientSecret:
            existingSecret: "generated--dex-argo-server-client"
            existingSecretKey: "client_secret"
            generateSecret: true
    oauth2Proxy:
      cookie:
        secret:
          existingSecret: "generated--oauth2-proxy-cookie-secret"
          existingSecretKey: "cookie_secret"
          generateSecret: true
  deploykf_dashboard:
    namespace: deploykf-dashboard
  deploykf_istio_gateway:
    namespace: deploykf-istio-gateway
    extraManifests: []
    gateway:
      hostname: <Redacted>
      ports:
        http: 8080
        https: 8443
      selectorLabels:
        app: deploykf-gateway
        istio: deploykf-gateway
    gatewayDeployment:
      serviceAccount:
        name: deploykf-gateway
        annotations: {}
    gatewayService:
      name: deploykf-gateway
      annotations: {}
      type: LoadBalancer
  deploykf_profiles_generator:
    profileDefaults:
      ## a common prefix to add to all profile names
      ##
      profileNamePrefix: ""

      ## the default access for members of profiles, when not explicitly specified
      ##  - `role`: the Kubernetes RBAC role to bind to the user in the profile namespace
      ##      - "edit": binds "ClusterRole/kubeflow-edit" (can view/create/delete resources)
      ##      - "view": binds "ClusterRole/kubeflow-view" (cam view resources)
      ##  - `notebooksAccess`: if the user can ~connect~ to kubeflow notebooks in the profile
      ##                       note, the ability to create/delete notebook resources is controlled by `role`
      ##
      memberAccess:
        role: view
        notebooksAccess: false

      ## the default list of plugins for profiles, when not explicitly specified
      ##  - each entry is a map with the following keys:
      ##     - `kind`: the kind of plugin
      ##         - "AwsIamForServiceAccount": manages AWS IRSA for the profile namespace
      ##         - "WorkloadIdentity": manages GCP WorkloadIdentity for the profile namespace
      ##     - `spec`: a map of plugin-specific configurations
      ##         - spec for AwsIamForServiceAccount:
      ##           https://github.com/kubeflow/kubeflow/blob/v1.7.0/components/profile-controller/controllers/plugin_iam.go#L30
      ##         - spec for WorkloadIdentity:
      ##           https://github.com/kubeflow/kubeflow/blob/v1.7.0/components/profile-controller/controllers/plugin_workload_identity.go#L39
      ##  - override these defaults for a specific profile by setting `plugins` in that profile,
      ##    to disable all plugins for that profile, set an empty list `[]`
      ##
      plugins: []

      ## the default resource quota for profiles, when not explicitly specified
      ##  - spec for ResourceQuotaSpec:
      ##    https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#resourcequotaspec-v1-core
      ##  - override these defaults for a specific profile by setting `resourceQuotaSpec` in that profile,
      ##    to disable resource quotas for that profile, set an empty map `{}`
      ##
      resourceQuotaSpec: {}

      ## the default tool configs for profiles
      ##
      tools:
        ## the default Kubeflow Pipelines configs for profiles
        ##
        kubeflowPipelines:
          ## the default Kubeflow Pipelines object store auth configs for profiles
          ##  - the behaviour of these configs depends on `kubeflow_tools.kubeflow_pipelines.objectStore`
          ##  - override these defaults for a specific profile by setting `tools.kubeflowPipelines.objectStoreAuth` in that profile
          ##
          objectStoreAuth:
            existingSecret: "kubeflow-pipelines--profile-object-store-auth--{profile_name}"
            existingSecretNamespace: ""
            existingSecretAccessKeyKey: "AWS_ACCESS_KEY"
            existingSecretSecretKeyKey: "AWS_SECRET_KEY"
    users:
      - id: <Redacted>
        email: "<Redacted>"
    groups:
      - id: admin
        users:
          - <Redacted>
      - id: staff
        users:
          - <Redacted>
    profiles:
      - name: <Redacted>
        members:
          - group: admin
            access:
              role: edit
              notebooksAccess: true
          - group: staff
            access:
              role: edit
              notebooksAccess: true
      - name: <Redacted>
        members:
          - user: <Redacted>
            access:
              role: edit
              notebooksAccess: true
deploykf_opt:
  deploykf_minio:
    enabled: false
  deploykf_mysql:
    enabled: false
kubeflow_dependencies:
  kubeflow_argo_workflows:
    enabled: true
    namespace: kubeflow-argo-workflows
kubeflow_tools:
  katib:
    enabled: true
    mysql:
      useExternal: true
      host: "<Redacted>"
      port: 3306
      auth:
        existingSecret: "kubeflow-mysql-auth"
        existingSecretUsernameKey: "MYSQL_USER"
        existingSecretPasswordKey: "MYSQL_PASS"
    mysqlDatabase: katib
  notebooks:
    enabled: true
    spawnerFormDefaults: {}
  pipelines:
    enabled: true
    bucket:
      name: kubeflow-prod
      region: ""
    objectStore:
      useExternal: true
      host: minio.minio-operator.svc.cluster.local
      port: ""
      useSSL: true
      auth:
        fromEnv: false
        existingSecret: "kubeflow-pipelines--backend-object-store-auth"
        existingSecretAccessKeyKey: "ACCESS_KEY"
        existingSecretSecretKeyKey: "SECRET_KEY"
    mysql:
      useExternal: true
      host: "<Redacted>"
      port: 3306
      auth:
        existingSecret: "kubeflow-mysql-auth"
        existingSecretUsernameKey: "MYSQL_USER"
        existingSecretPasswordKey: "MYSQL_PASS"
    mysqlDatabases:
      cacheDatabase: kfp_cache
      metadataDatabase: kfp_metadata
      pipelinesDatabase: kfp_pipelines
    profileResourceGeneration:
      ## if a PodDefault named "kubeflow-pipelines-api-token" should be generated in each profile namespace
      ##  - the generated PodDefault will mount a serviceAccountToken volume which can be used to authenticate
      ##    with the Kubeflow Pipelines API on Pods which have a `kubeflow-pipelines-api-token` label with value "true"
      ##  - for more information, see the "Full Kubeflow (from inside cluster)" section of the following page:
      ##    https://www.kubeflow.org/docs/components/pipelines/v1/sdk/connect-api/
      ##  - the PodDefault will NOT be generated if `kubeflow_tools.poddefaults_webhook.enabled` is false,
      ##    regardless of this setting
      ##
      kfpApiTokenPodDefault: false
  poddefaults_webhook:
    enabled: true
  tensorboards:
    enabled: true
  training_operator:
    enabled: true
  volumes:
    enabled: true
```
