### ISSUE TITLE
kf-core--deploykf-auth secret is not getting created automatically

### ISSUE THREAD

**Issue by tppalani** [deployKF/deployKF#221]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

v0.1.5

### Kubernetes Distribution

EKS

### Kubernetes Version

```shell
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.8-eks-a737599
```

### Description

I have successfully configured application deploykf-app-of-apps application while synicing the application from one after another fro argocd UI page i got stuck to sync the following application dkf-core--deploykf-auth, both pod got failed dex and oauth.

can you please help me on this, here the secret i can find in my deploy-auth namespace by default.

```
$ k get secret -n deploykf-auth
NAME                  TYPE     DATA   AGE
dex-config            Opaque   1      54m
oauth2-proxy-config   Opaque   1      54m
```

### Relevant Logs

```shell
NAMESPACE deploykf-auth   
IMAGES docker.io/istio/proxyv2:1.17.8-distrolessquay.io/oauth2-proxy/oauth2-proxy:v7.6.0
STATE - CreateContainerConfigError
STATE DETAILS - secret "generated--dex-oauth2-proxy-client" not found
CONTAINER STATE 
istio-init - Container is terminated because of Completed. It exited with exit code 0. It is not started.
istio-proxy - Container is running. It is started and ready.
oauth2-proxy - Container is waiting because of CreateContainerConfigError. It is not started and not ready.

HEALTH -  secret "generated--dex-oauth2-proxy-client" not found
```

### deployKF Values (Optional)

```yaml
## dex OpenID Connect clients
      ##
      clients:

        ## OpenID client for oauth2-proxy (deployKF Dashboard)
        oauth2Proxy:
          clientId: "oauth2-proxy"
          clientSecret:
            existingSecret: "generated--dex-oauth2-proxy-client"
            existingSecretKey: "client_secret"
            generateSecret: true
```
