### ISSUE TITLE
deployKF  external object's service accounts and IRSA mapping 

### ISSUE THREAD

**Issue by tppalani** [deployKF/deployKF#226]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

v0.1.5

### Kubernetes Distribution

EKS

### Kubernetes Version

```shell
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

### Description

I'm trying to configure the external storage objects S3, might be i'm missed some steps in my values.yaml. According to this document - i have create each IAM role and i verified AWS console role has been created.

1. ml-pipeline
2. ml-pipeline-ui
3. argo-server
4. argo-workflow-controller

Next steps is i need update the sample.values.yaml to add above service account annotation to make it add in the service accounts in kubeflow namespaces, please find the below yaml file.

in my case after sync argo-app ml-pipeline and ml-pipeline-ui has the same ARN value instead to use respective role ARN values. 

### Relevant Logs

```shell
ml-pipeline pod logs

I1027 05:15:54.097479       7 client_manager.go:170] Initializing client manager
I1027 05:15:54.097743       7 config.go:57] Config DBConfig.MySQLConfig.ExtraParams not specified, skipping
```

### deployKF Values (Optional)

```yaml
## --------------------------------------
  ##      deploykf-profiles-generator
  ## --------------------------------------
  deploykf_profiles_generator:

    ## profile defaults
    ##
    profileDefaults:
      #profileNamePrefix: ""
    #   memberAccess:
    #     role: view
    #     notebooksAccess: false
       
    kubeflow-ml-pipeline:
      plugins:
        - kind: AwsIamForServiceAccount
          spec:
            awsIamRole: "arn:aws:iam::123456789123:role/kubeflow-ml-pipeline-iam-policy"
            AnnotateOnly: true
    
    ml-pipeline-ui:
       plugins:
         - kind: AwsIamForServiceAccount
           spec:
             awsIamRole: "arn:aws:iam::123456789123:role/kubeflow-ml-pipeline-ui-iam-policy"
             AnnotateOnly: true

    argo-server:
       plugins:
         - kind: AwsIamForServiceAccount
           spec:
             awsIamRole: "arn:aws:iam::123456789123:role/kubeflow-ml-pipeline-argo-server-iam-policy"
             AnnotateOnly: true

    argo-workflow-controller:
       plugins:
         - kind: AwsIamForServiceAccount
           spec:
             awsIamRole: "arn:aws:iam::123456789123:role/kubeflow-pipeline-argo-workflow-controller-iam-policy"
             AnnotateOnly: true
    
            resourceQuotaSpec: {}

      ## the default tool configs for profiles
      ##
      tools:

        ## the default Kubeflow Pipelines configs for profiles
        ##
        kubeflowPipelines:
          objectStoreAuth:
            existingSecret: "kubeflow-pipelines--profile-object-store-auth--{profile_name}"
            existingSecretNamespace: ""
            existingSecretAccessKeyKey: "access_key"
            existingSecretSecretKeyKey: "secret_key"

    ## user entities
    ##  - a list of users that can be referenced when defining profile members
    ##  - each element is a map with the following keys:
    ##     - `id`: a unique identifier for the user
    ##     - `email`: the email of the user (must exactly match the email from your identity provider)
    ##
    users:
     - id: user1
       email: "user1@address.com"
    groups:
      - id: KF-ADMIN
        users:
          - user1     

    profiles:
     - name: caas-admin
       members:
        - group: KF-ADMIN
          access:
            role: edit
            notebooksAccess: true
       plugins:
        # - kind: AwsIamForServiceAccount
        #   spec:
        #     #awsIamRole: arn:aws:iam::123456789123:role/kubeflow-pipeline-bucket-iam-policy
        #     awsIamRole: arn:aws:iam::123456789123:role/kubeflow-ml-pipeline-ui-iam-policy
        #     AnnotateOnly: true

## --------------------------------------------------------------------------------
##
##                                   deploykf-opt
##
## --------------------------------------------------------------------------------
deploykf_opt:

  ## --------------------------------------
  ##            deploykf-minio
  ## --------------------------------------
  deploykf_minio:
    enabled: false
    rootUser:
      serviceAccounts: []

    buckets: []

   
    policies: []

  ## --------------------------------------
  ##            deploykf-mysql
  ## --------------------------------------
  deploykf_mysql:
    enabled: false
    rootUser:
    kubeflowUser:

## --------------------------------------------------------------------------------
##
##                              kubeflow-dependencies
##
## --------------------------------------------------------------------------------
kubeflow_dependencies:

  ## --------------------------------------
  ##        kubeflow-argo-workflows
  ## --------------------------------------
  kubeflow_argo_workflows:
    controller:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: "arn:aws:iam::123456789123:role/kubeflow-argo-workflow-bucket-iam-policy"
    server:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: "arn:aws:iam::123456789123:role/kubeflow-argo-workflow-bucket-iam-policy"
    enabled: true
    namespace: kubeflow-argo-workflows


## --------------------------------------------------------------------------------
##
##                                  kubeflow-tools
##
## --------------------------------------------------------------------------------
kubeflow_tools:
  

  ## --------------------------------------
  ##                 katib
  ## --------------------------------------
  katib:
    enabled: true
    namespace: deploykf-mysql
    mysql:
      useExternal: true
      host: "rds.amazonaws.com"
      port: 3306
      auth:
        existingSecret: "katib-mysql-secret"
        existingSecretUsernameKey: "username"
        existingSecretPasswordKey: "password"

    ## mysql database name
    ##
    mysqlDatabase: katib


  ## --------------------------------------
  ##               notebooks
  ## --------------------------------------
  notebooks:
    enabled: true

    ## notebook spawner configs
    ##  - these configs directly become the `spawner_ui_config.yaml` in the jupyter-web-app
    ##
    spawnerFormDefaults: {}


  ## --------------------------------------
  ##               pipelines
  ## --------------------------------------
  pipelines:
    serviceAccounts:
      apiServer:
        annotations:
          eks.amazonaws.com/role-arn: "arn:aws:iam::123456789123:role/kubeflow-ml-pipeline-iam-policy"
      frontend:
        annotations:
          eks.amazonaws.com/role-arn: "arn:aws:iam::123456789123:role/kubeflow-ml-pipeline-iam-policy"
    enabled: true

    ## storage bucket configs
    ##
    bucket:
      name: kubeflow-rds-s3
      region: "us-east-2"
    ##
    objectStore:
      useExternal: true
      host: s3.us-east-2.amazonaws.com
      useSSL: true
      auth:
        fromEnv: true
    mysql:
      useExternal: true
      host: "rds.amazonaws.com"
      port: 3306
      auth:
        existingSecret: "pipelines-mysql-secret"
        existingSecretUsernameKey: "username"
        existingSecretPasswordKey: "password"

    ## mysql database names
    ##
    mysqlDatabases:
      cacheDatabase: kfp_cache
      metadataDatabase: kfp_metadata
      pipelinesDatabase: kfp_pipeline

    ## profile resource generation configs
    ##
    profileResourceGeneration:
      kfpApiTokenPodDefault: false
```

**Comment by ishaan-mehta** [comment]
Seeing the same issue with the `ml-pipeline` pod after configuring deployKF to use an external object store (I am using Azure Blob Storage with s3proxy as a proxy).

The container is failing with exit code 137, shows the same logs as you, and results in an identical message on the dashboard when accessing Kubeflow Pipelines.

Increasing memory and CPU requests has not helped, so I am not sure what the issue is.

**Comment by tppalani** [comment]
Hi @thesuperzapper 

can you help us to proceeds further that would be really helpful.

**Comment by thesuperzapper** [comment]
@ishaan-mehta @tppalani I think the `ml-pipeline` code is getting stuck somewhere before/during [this section of its code](https://github.com/kubeflow/pipelines/blob/f8973d27cc3b7328b31222ac26b9a6361f8ed16d/backend/src/apiserver/client_manager/client_manager.go#L498-L507), because on a working deployment I see `We already own <BUCKET_NAME>`:

```text
ml-pipeline-api-server I1105 18:18:40.278826       7 client_manager.go:170] Initializing client manager
ml-pipeline-api-server I1105 18:18:40.278918       7 config.go:57] Config DBConfig.MySQLConfig.ExtraParams not specified, skipping
ml-pipeline-api-server I1105 18:18:40.375224       7 client_manager.go:503] We already own kubeflow-pipelines
...
```

So it's probably failing to check if the bucket exists.

## Request for you

Could both of you see if there are more logs when you use the `kubectl get logs --previous` flag to get the logs from the last crash of the Pod and share them?

Hopefully it gives you more info about what specifically failed before the Pod crashed.

## Possible Solution: Real S3

If you are using real S3, it is probably because your IAM policy is not what we [listed on our docs](https://www.deploykf.org/guides/external/object-store/#bucket-iam-policies):

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        \/ \/ this part is important \/\/
        "s3:GetBucketLocation",
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:aws:s3:::<BUCKET_NAME>"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject"
      ],
      "Resource": [
        "arn:aws:s3:::<BUCKET_NAME>/artifacts/*",
        "arn:aws:s3:::<BUCKET_NAME>/pipelines/*",
        "arn:aws:s3:::<BUCKET_NAME>/v2/artifacts/*"
      ]
    }
  ]
}
```

## Possible Solution: S3Proxy (Azure Blob Store)

If you are using something like [s3proxy](https://github.com/gaul/s3proxy) with Azure Blob Store as the backend, ensure you have set the bucket name in s3proxy to the same thing as you set in deployKF values.

And if that does not work there might be some kind of issue with S3Proxy, where it does not correctly support the [Bucket `HEAD`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html) API, which is what `ml-pipeline` is using to check the bucket exists.

**Comment by ishaan-mehta** [comment]
Hi @thesuperzapper — thanks, checking out the `HeadBucket` thing. Just to confirm, does that mean you don't know of anyone that has successfully used s3proxy with deployKF before? Might save us some time in case we suspect that is the issue.

Meanwhile, here are the logs given by the `kubectl` command (unfortunately the same ones visible in Argo CD):
```
➜ kubectl logs --previous ml-pipeline-58db88b96f-mng4z -n kubeflow
I1108 20:44:16.305977       7 client_manager.go:170] Initializing client manager
I1108 20:44:16.306080       7 config.go:57] Config DBConfig.MySQLConfig.ExtraParams not specified, skipping
```

**Comment by ishaan-mehta** [comment]
Hi @thesuperzapper @tppalani — it is working for me now!

I hit the `s3proxy` service with a bucket `HEAD` request from one of the healthy Kubeflow Pipelines pods, and it worked successfully. So that wasn't the issue. Results:
```
➜ kubectl exec -i ml-pipeline-visualizationserver-8686474bb9-bgkhl -n team-1 -- curl -s -I http://s3proxy.s3proxy.svc.cluster.local:8080/dkf
HTTP/1.1 200 OK
date: Fri, 08 Nov 2024 22:15:24 GMT
x-amz-request-id: 4442587FB7D0A2F9
content-length: 0
server: envoy
x-envoy-upstream-service-time: 181
```

I also confirmed that the bucket name whose existence I checked with the above command is the same as the one I added to my deployKF values.

However, it turned out the issue was with my object store config:
```
  ## --------------------------------------
  ##               pipelines
  ## --------------------------------------
  pipelines:
    bucket:
      name: dkf
    objectStore:
      useExternal: true
      
      ## this specifies the S3-compatible endpoint of your object store
      ##  - for S3 itself, you may need to use the region-specific endpoint
      ##  - don't set a port unless it is non-standard
      host: "http://s3proxy.s3proxy.svc.cluster.local"
      port: 8080
```

I changed that to this (after setting up the s3proxy with port 80 instead of 8080):
```
  ## --------------------------------------
  ##               pipelines
  ## --------------------------------------
  pipelines:
    bucket:
      name: dkf
    objectStore:
      useExternal: true
      
      ## this specifies the S3-compatible endpoint of your object store
      ##  - for S3 itself, you may need to use the region-specific endpoint
      ##  - don't set a port unless it is non-standard
      host: "s3proxy.s3proxy.svc.cluster.local"
      port:
```

So the issue was with either the `http://` or the non-standard port or both.

I notice that in `consolidated/manifests/kubeflow-tools/pipelines/resources/profile-resources.yaml`, there is the following note, but I am not sure if it means we are not allowed to use a non-standard port:
```
            - name: AWS_S3_ENDPOINT
              ## NOTE: we use hostname only, KFP doesn't allow ports in the s3 endpoint config
              value: "http://s3proxy.s3proxy.svc.cluster.local"
```

**Comment by tppalani** [comment]
Hi @thesuperzapper  @ishaan-mehta 

i have just revisited the my terraform code i have created inline policy as like below and i have noticed that bucket arn also copied and updated in the below code and its has all the required policy to get and list the s3 bucket.


```
kubectl logs -n kubeflow ml-pipeline-7bfddf7876-lzjwr --previous
I1109 09:49:11.274171       7 client_manager.go:170] Initializing client manager
I1109 09:49:11.274335       7 config.go:57] Config DBConfig.MySQLConfig.ExtraParams not specified, skipping
```

Component	                         Namespace	       ServiceAccount Name
Kubeflow Pipelines Backend	kubeflow	              ml-pipeline
Kubeflow Pipelines Backend	kubeflow	              ml-pipeline-ui
User Profiles	                      {profile_name}	     default-editor

1. ml-pipeline

```
// Kubeflow Pipelines Backend	kubeflow	ml-pipeline

locals {
  kubeflow-ml-pipeline-iam-policy = replace(data.aws_eks_cluster.cluster.identity[0].oidc[0].issuer, "https://", "")
}

module "kubeflow-ml-pipeline-iam-policy" {
  source              = "terraform-aws-iam-role/aws"
  version             = "0.1.5"
  tags                = module.mandatory_tags.tags
  iam_role_name       = "kubeflow-ml-pipeline-iam-policy"
  role_description    = "kubeflow-ml-pipeline-iam-policy"
  assume_role_policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Effect" : "Allow",
        "Principal" : {
          "Federated" : "arn:aws:iam::${data.aws_caller_identity.current.account_id}:oidc-provider/${local.kubeflow-ml-pipeline-iam-policy}"
        },
        "Action" : "sts:AssumeRoleWithWebIdentity",
        "Condition" : {
          "StringEquals" : { 
            "${local.kubeflow-ml-pipeline-iam-policy}:aud": "sts.amazonaws.com",
            "${local.kubeflow-ml-pipeline-iam-policy}:sub": "system:serviceaccount:kubeflow:ml-pipeline",
          }
        }
      }
    ]
  })
  inline_policy = [{
    name = "kubeflow-ml-pipeline-iam-policy"
    policy = jsonencode({
        "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetBucketLocation",
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:aws:s3:::caas-kubeflow-rds-s3"
        
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:Get*",
        "s3:Put*",
        "s3:Delete*"
      ],
      "Resource": [
        "arn:aws:s3:::caas-kubeflow-rds-s3/artifacts/*",
        "arn:aws:s3:::caas-kubeflow-rds-s3/pipelines/*",
        "arn:aws:s3:::caas-kubeflow-rds-s3/v2/artifacts/*"
      ]
    }
  ]
    })  
  }]
}
```

2. ml-pipeline-ui

```
// kubeflow-ml-pipeline-ui-iam-policy (Kubeflow pipeline backend)

locals {
  kubeflow-ml-pipeline-ui-iam-policy = replace(data.aws_eks_cluster.cluster.identity[0].oidc[0].issuer, "https://", "")
  
}

module "kubeflow-ml-pipeline-ui-iam-policy" {
  source              = "terraform-aws-iam-role/aws"
  version             = "0.1.5"
  tags                = module.mandatory_tags.tags
  iam_role_name       = "kubeflow-ml-pipeline-ui-iam-policy"
  role_description    = "kubeflow-ml-pipeline-ui-iam-policy"
  assume_role_policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Effect" : "Allow",
        "Principal" : {
          "Federated" : "arn:aws:iam::${data.aws_caller_identity.current.account_id}:oidc-provider/${local.kubeflow-ml-pipeline-ui-iam-policy}"
        },
        "Action" : "sts:AssumeRoleWithWebIdentity",
        "Condition" : {
          "StringEquals" : { 
            "${local.kubeflow-ml-pipeline-ui-iam-policy}:aud": "sts.amazonaws.com",
            "${local.kubeflow-ml-pipeline-ui-iam-policy}:sub": "system:serviceaccount:kubeflow:ml-pipeline-ui"
          }
        }
      }
    ]
  })
  inline_policy = [{
    name = "kubeflow-ml-pipeline-ui-iam-policy"
    policy = jsonencode({
        "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetBucketLocation",
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:aws:s3:::caas-kubeflow-rds-s3"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject"
      ],
      "Resource": [
        "arn:aws:s3:::caas-kubeflow-rds-s3/artifacts/*",
        "arn:aws:s3:::caas-kubeflow-rds-s3/pipelines/*",
        "arn:aws:s3:::caas-kubeflow-rds-s3/v2/artifacts/*"
      ]
    }
  ]
    })  
  }]
}
```

3. user.profile

```
  // kubeflow-pipeline-profile-iam-policy (PROFILE namespaces)
locals {
  kubeflow-pipeline-profile-iam-policy = replace(data.aws_eks_cluster.cluster.identity[0].oidc[0].issuer, "https://", "")
}

module "kubeflow-pipeline-profile-iam-policy" {
  source              = "terraform-aws-iam-role/aws"
  version             = "0.1.5"
  tags                = module.mandatory_tags.tags
  iam_role_name       = "kubeflow-pipeline-profile-iam-policy"
  role_description    = "kubeflow-pipeline-profile-iam-policy"
  assume_role_policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Effect" : "Allow",
        "Principal" : {
          "Federated" : "arn:aws:iam::${data.aws_caller_identity.current.account_id}:oidc-provider/${local.kubeflow-pipeline-profile-iam-policy}"
        },
        "Action" : "sts:AssumeRoleWithWebIdentity",
        "Condition" : {
          "StringEquals" : { 
            "${local.kubeflow-pipeline-profile-iam-policy}:aud": "sts.amazonaws.com",  
            "${local.kubeflow-pipeline-profile-iam-policy}:sub": "system:serviceaccount:caas-admin:default-editor"
          }
        }
      }
    ]
  })
  inline_policy = [{
    name = "kubeflow-pipeline-profile-iam-policy"
    policy = jsonencode({
        "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetBucketLocation",
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:aws:s3:::caas-kubeflow-rds-s3"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject"
      ],
      "Resource": [
        "arn:aws:s3:::caas-kubeflow-rds-s3/artifacts/caas-admin/*",
        "arn:aws:s3:::caas-kubeflow-rds-s3/v2/artifacts/caas-admin/*"
      ]
    }
  ]
    })  
  }]
}
```

**Comment by tppalani** [comment]
@thesuperzapper  @ishaan-mehta 

Here is the testing 

values.yaml

```
bucket:
      name: caas-kubeflow-rds-s3
      region: "us-east-2"
    objectStore:
      useExternal: true
      host: s3.us-east-2.amazonaws.com
      useSSL: true
      auth:
        fromEnv: true
```

I have tried both way using curl with http and without too both are having 403 forbidden, i'm thinking due to this  my ml-pipeline-api pod is is throwing below error ?

ml-pipeline-api-pod  logs in kubeflow namespace

```
I1109 13:19:51.722900       7 client_manager.go:170] Initializing client manager
I1109 13:19:51.723145       7 config.go:57] Config DBConfig.MySQLConfig.ExtraParams not specified, skipping
```

pipeline visualizationserver curl testing from caas-admin namespace (profile name)

```
 kubectl exec -i ml-pipeline-visualizationserver-9cdd7b898-h7kc5 -n caas-admin -- curl -s -I s3.us-east-2.amazonaws.com/caas-kubeflow-rds-s3
HTTP/1.1 403 Forbidden
x-amz-bucket-region: us-east-2
x-amz-request-id: HG42W3ZB0VPAZ6CS
x-amz-id-2: esEPnykrQgJ8wTh8lTRRmM4KfnDQrDg6TnDX962lPdCOBliWKgCsv6HagvxWhI0HNi/a/v1VT2E=
content-type: application/xml
date: Sat, 09 Nov 2024 13:14:36 GMT
server: envoy
x-envoy-upstream-service-time: 19
transfer-encoding: chunked
```

**Comment by tppalani** [comment]
Hi @thesuperzapper 

I have just created sample pod to map with my existing service account which is annotated with IRSA i can able to list the file from my s3 bucket but still ml-pipeline pod is not healthy are you thinking is this IRSA issue or something different.

sample pod yaml

```
apiVersion: batch/v1
kind: Job
metadata:
  name: eks-iam-test-s3
  namespace: kubeflow
spec:
  template:
    metadata:
      labels:
        app: eks-iam-test-s3
    spec:
      serviceAccountName: ml-pipeline
      containers:
      - name: eks-iam-test
        image: amazon/aws-cli:latest
        command: ["sh", "-c", "aws s3 ls s3://caas-kubeflow-rds-s3"]
      restartPolicy: Never
```

```
 kubectl logs -l app=eks-iam-test-s3 -n kubeflow
2024-10-28 11:04:05      39522 agent.log
```

ml-pipeline api server pod logs

```
I1115 12:44:42.912953       7 client_manager.go:170] Initializing client manager
I1115 12:44:42.913196       7 config.go:57] Config DBConfig.MySQLConfig.ExtraParams not specified, skipping
```

**Comment by rahch1982** [comment]
Hi all! 

Has anyone found a solution for the issue? Any updates or insights would be greatly appreciated! 

I'm currently facing a similar issue when implementing S3 as object store for Kubeflow Pipelines using IRSA-Based Authentication. I've followed instructions documented [here](https://www.deploykf.org/guides/external/object-store/#bucket-iam-policies).

However, the `ml-pipeline-api-server` container is failing with exit code 2. The pod logs show the following error:

```
I1212 15:29:29.780122       7 client_manager.go:170] Initializing client manager
I1212 15:29:29.780249       7 config.go:57] Config DBConfig.MySQLConfig.ExtraParams not specified, skipping
F1212 15:29:30.317281       7 client_manager.go:500] Failed to check if Minio bucket exists. Error: Access Denied.

goroutine 1 [running]:
github.com/golang/glog.Fatalf(...)
        /go/pkg/mod/github.com/golang/glog@v1.1.0/glog.go:585
...
```

Our `deploykf` app of apps definition includes, among other things, the following configuration in order to allow Kubeflow Pipelines connect to s3 using IRSA-based authentication:

```
            ## --------------------------------------------------------------------------------
            ##                                   deploykf-opt
            ## --------------------------------------------------------------------------------
            deploykf_opt:

              ## --------------------------------------
              ##            deploykf-minio
              ## --------------------------------------
              deploykf_minio:
                enabled: false

            ## --------------------------------------------------------------------------------
            ##                                  kubeflow-tools
            ## --------------------------------------------------------------------------------
            kubeflow_tools:
              ## --------------------------------------
              ##               pipelines
              ## --------------------------------------
              pipelines:
                enabled: true

                serviceAccounts:
                  apiServer:
                    annotations:
                      eks.amazonaws.com/role-arn: "arn:aws:iam::<accountNumber>:role/<IAMRoleName>"
                  frontend:
                    annotations:
                      eks.amazonaws.com/role-arn: "arn:aws:iam::<accountNumber>:role/<IAMRoleName>"

                bucket:
                  name: deploykf-kubeflow-pipelines-dev
                  region: "us-east-2"

                objectStore:
                  useExternal: true
                  host: s3.us-east-2.amazonaws.com
                  useSSL: true

                auth:
                  fromEnv: true
```

I have validated that the `serviceaccount` is able to assume the IAM role, and has access to the specified bucket using the same approach:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: eks-iam-access-s3
  namespace: kubeflow
spec:
  template:
    metadata:
      labels:
        app: eks-iam-access-s3
    spec:
      serviceAccountName: ml-pipeline
      containers:
      - name: eks-iam-access
        image: amazon/aws-cli:latest
        command: ["sh", "-c", "aws s3 ls s3://deploykf-kubeflow-pipelines-dev"]
      restartPolicy: Never
```

Logs show a successful response:

```
[ec2-user@ip-10-49-90-16 ~]$ kubectl -n kubeflow logs eks-iam-access-s3-b2l9r
2024-12-12 14:49:27        103 sample.yaml
```

IAM Policy assigned to the Role is the following:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetBucketLocation",
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:aws:s3:::deploykf-kubeflow-pipelines-dev"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject"
      ],
      "Resource": [
        "arn:aws:s3:::deploykf-kubeflow-pipelines-dev/artifacts/*",
        "arn:aws:s3:::deploykf-kubeflow-pipelines-dev/pipelines/*",
        "arn:aws:s3:::deploykf-kubeflow-pipelines-dev/v2/artifacts/*"
      ]
    }
  ]
}
```

### deployKF Version
v0.1.5

### Kubernetes Distribution
EKS version 1.30

### ml-pipeline-api-server image and tag
ghcr.io/deploykf/kubeflow-pipelines/api-server:2.1.0-deploykf.0
