### ISSUE TITLE
Install Kubeflow without Istio

### ISSUE THREAD

**Issue by JWebDev** [deployKF/deployKF#227]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.5

### Kubernetes Distribution

Bare Metal

### Kubernetes Version

```shell
1.29.4
```

### Description

I'm trying to install kubeflow using your intsallator.
But it's a bit not thought out/done all the way through or it's a bug.

My main goal is to throw istio off the intsallator. Hardcore to build istio to the deployment is a serious misstep. Not everyone needs it and it should be quickly disabled, which is not the case in this case.

I read your documentation, you write that Istio is an optional component. => https://www.deploykf.org/guides/cluster-dependencies/#cluster-dependency-guides
At the same time istio-gateway is not optional, not clear why. https://github.com/deployKF/deployKF/blob/29ac97a8727d4da10f456263d755e391faface2d/generator/helpers/check-values--required-components.tpl#L26

I can't install the kubeflow the way through. 

It also says that cert-manager is optional, and if istio-gateway is not optional, then cert-manager becomes required. Because you need to generate a certificate.

It looks like you tested only happy path. Sorry, but it took me half a day to try to install everything quickly and automatically from your words.

The main question remains open. Is it possible to install Kubeflow without throwing away Istio completely? If yes, then how should the values.yaml looks like?

If not, please write about it. And if not, is it possible to configure istio-gateway-service on ClusterIP. This didn't work for me either, even though I changed LoadBalancer to ClusterIP. 

At the moment with this configuration I got the Service and it seems to have passed with the certificates, But for some reason istio-gateway does not start because the deployment image is somehow "auto".

```
 containerStatuses:
    - name: istio-proxy
      state:
        waiting:
          reason: ImagePullBackOff
          message: Back-off pulling image "auto"
      lastState: {}
      ready: false
      restartCount: 0
      image: auto
      imageID: ''
      started: false
```

Thanks.

### deployKF Values (Optional)

```yaml
argocd:
  appNamePrefix: ""
  namespace: argocd
  project: default
  source:
    repo:
      url: ""
      revision: ""
      path: ""
  destination:
    server: https://kubernetes.default.svc
    name: ""
  
  deploykf_dependencies:
    cert_manager:
      enabled: true
      namespace: cert-manager
      extraManifests: []
      clusterIssuer:
        enabled: true
        issuerName: deploykf-gateway-issuer
    
    istio:
      enabled: false
      namespace: istio-system
    
    kyverno:
      enabled: false
      namespace: kyverno
  
  
  deploykf_core:
    deploykf_auth:
      namespace: deploykf-auth
      dex:
        connectors: []
        clients:
          
          ## OpenID client for oauth2-proxy (deployKF Dashboard)
          oauth2Proxy:
            clientId: "oauth2-proxy"
            clientSecret:
              existingSecret: "generated--dex-oauth2-proxy-client"
              existingSecretKey: "client_secret"
              generateSecret: true
          
          ## OpenID client for Minio Console
          minioConsole:
            clientId: "minio-console"
            clientSecret:
              existingSecret: "generated--dex-minio-console-client"
              existingSecretKey: "client_secret"
              generateSecret: true
          
          ## OpenID client for Argo Server
          argoServer:
            clientId: "argo-server"
            clientSecret:
              existingSecret: "generated--dex-argo-server-client"
              existingSecretKey: "client_secret"
              generateSecret: true
      
      oauth2Proxy:
        cookie:
          secret:
            existingSecret: "generated--oauth2-proxy-cookie-secret"
            existingSecretKey: "cookie_secret"
            generateSecret: true
    
    
    deploykf_dashboard:
      namespace: deploykf-dashboard
    
    deploykf_istio_gateway:
      namespace: deploykf-istio-gateway
      extraManifests: []
      gateway:
        enabled: false
        hostname: deploykf.example.com
        ports:
          http: 8080
          https: 8443
        selectorLabels:
          app: deploykf-gateway
          istio: deploykf-gateway
      gatewayDeployment:
        serviceAccount:
          name: deploykf-gateway
          annotations: {}
      gatewayService:
        name: deploykf-gateway
        annotations: {}
        type: ClusterIP
    
    
    deploykf_profiles_generator:
      profileDefaults:
        profileNamePrefix: ""
        memberAccess:
          role: view
          notebooksAccess: false
        plugins: []
        resourceQuotaSpec: {}
        tools:
          kubeflowPipelines:
            objectStoreAuth:
              existingSecret: "kubeflow-pipelines--profile-object-store-auth--{profile_name}"
              existingSecretNamespace: ""
              existingSecretAccessKeyKey: "access_key"
              existingSecretSecretKeyKey: "secret_key"
  
  deploykf_opt:
    
    deploykf_minio:
      enabled: true
      namespace: deploykf-minio
      rootUser:
        existingSecret: "generated--deploykf-minio-root-user"
        existingSecretUsernameKey: "username"
        existingSecretPasswordKey: "password"
        generateSecret: true
        serviceAccounts: []
      buckets: []
      policies: []
    deploykf_mysql:
      enabled: true
      namespace: deploykf-mysql
      rootUser:
        existingSecret: "generated--deploykf-mysql-root-user"
        existingSecretPasswordKey: "password"
        generateSecret: true
      kubeflowUser:
        existingSecret: "generated--deploykf-mysql-kubeflow-user"
        existingSecretUsernameKey: "username"
        existingSecretPasswordKey: "password"
        generateSecret: true
  
  kubeflow_dependencies:
    
    kubeflow_argo_workflows:
      enabled: true
      namespace: kubeflow-argo-workflows
  
  
  kubeflow_tools:
    katib:
      enabled: true
      mysql:
        useExternal: false
        host: "mysql.example.com"
        port: 3306
        auth:
          username: kubeflow
          password: password
          existingSecret: ""
          existingSecretUsernameKey: "username"
          existingSecretPasswordKey: "password"
      mysqlDatabase: katib
    
    
    notebooks:
      enabled: true
      
      spawnerFormDefaults: {}
    
    pipelines:
      enabled: true
      
      bucket:
        name: kubeflow-pipelines
        region: ""
      
      objectStore:
        useExternal: false
        host: s3.amazonaws.com
        port: ""
        useSSL: true
        
        
        auth:
          fromEnv: false
          accessKey: my-access-key
          secretKey: my-secret-key
          existingSecret: ""
          existingSecretAccessKeyKey: "AWS_ACCESS_KEY_ID"
          existingSecretSecretKeyKey: "AWS_SECRET_ACCESS_KEY"
      
      mysql:
        useExternal: false
        host: "mysql.example.com"
        port: 3306
        auth:
          username: kubeflow
          password: password
          existingSecret: ""
          existingSecretUsernameKey: "username"
          existingSecretPasswordKey: "password"
      
      
      mysqlDatabases:
        cacheDatabase: kfp_cache
        metadataDatabase: kfp_metadata
        pipelinesDatabase: kfp_pipelines
      
      profileResourceGeneration:
        
        kfpApiTokenPodDefault: false
    
    poddefaults_webhook:
      enabled: true
    
    tensorboards:
      enabled: true
    
    training_operator:
      enabled: true
    
    volumes:
      enabled: true
```
