### ISSUE TITLE
Exposing Gateway Service via Ingress

### ISSUE THREAD

**Issue by RahmanBadru** [deployKF/deployKF#234]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.5

### Kubernetes Distribution

AKS

### Kubernetes Version

```shell
Client Version: v1.28.15
Server Version: v1.29.4
```

### Description

I'm trying to expose the Gateway Service via Ingress, we have our custom tls , but i get a 502 Bad Gateway on the ingress. our tls supports domain k8.isw.la

### deployKF Values (Optional)

```yaml
deploykf_istio_gateway:
    namespace: deploykf-istio-gateway

    extraManifests: 
      - |
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: deploykf-gateway
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

            ## nginx wil NOT proxy the SNI by default
            ## see: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#backend-certificate-authentication
            nginx.ingress.kubernetes.io/proxy-ssl-name: "deploykf.k8.isw.la"
            nginx.ingress.kubernetes.io/proxy-ssl-server-name: "on"

            ## this config is needed due to a bug in ingress-nginx
            ## see: https://github.com/kubernetes/ingress-nginx/issues/6728
            nginx.ingress.kubernetes.io/proxy-ssl-secret: "deploykf-istio-gateway/k8-ingress-tls"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
        spec:
          tls:
            ## NOTE: this secret is created as part of the deployKF installation
            - secretName: "k8-ingress-tls"
          rules:
            - host: "deploykf.k8.isw.la"
              http:
                paths:
                  - path: "/"
                    pathType: Prefix
                    backend:
                      service:
                        name: "deploykf-gateway"
                        port:
                          name: https
            - host: "*.deploykf.k8.isw.la"
              http:
                paths:
                  - path: "/"
                    pathType: Prefix
                    backend:
                      service:
                        name: "deploykf-gateway"
                        port:
                          name: https
    charts:
      istioGateway:
        version: 1.16.0

    gateway:

      hostname: deploykf.k8.isw.la

      ports:
        http: 80
        https: 443

      ## the pod labels used by the gateway to find the ingress gateway deployment
      ##
      selectorLabels:
        app: deploykf-gateway
        istio: deploykf-gateway

    gatewayDeployment:
      serviceAccount:
        name: deploykf-gateway
        annotations: {}

    ## istio gateway service configs
    ##
    gatewayService:
      name: deploykf-gateway
      annotations: {}
      type: ClusterIP
```
