### ISSUE TITLE
Ability to configure replicas, affinity, nodeSelector and tolerations on every deployment

### ISSUE THREAD

**Issue by berglh** [deployKF/deployKF#251]
### Checks

- [x] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [x] This request is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### Motivation

We use our EKS (v1.30) cluster for multiple deployments, and have Karpenter node pools configured, usually with taints to prevent workloads running on specific Kubernetes nodes unless the deployment explicitly tolerates the taint. This prevents situations where deployments/replicasets/pods do not tolerate the taint are not scheduled to run on the same nodes as the `deployKF`. In our cluster, we are running Apache Spark clusters using Airflow. We have a default untainted node pool where these workloads end up by default, and currently, all the deployKF deployments will end up on the same nodes as our high-CPU usage ephemeral Apache Spark clusters.

This means, for each Helm chart installed or deployment, we have to set the [affinity](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/), [tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) to tolerate node pool/node group taints, and/or [nodeSelector](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/) configuration into the Helm chart values to correctly target a deployment at a specific class of dedicated nodes.

In addition to this, `cert-manager` and other dependencies for the deployKF distribution recommend running these services in [HA mode](https://cert-manager.io/docs/installation/best-practice/#high-availability) by increasing replicas and then it's inferred that we would be configuring PodAntiAffinity to ensure each deployment pod replica isn't running on the same node.

I have looked extensively in the [Discussions](https://github.com/deployKF/deployKF/issues/223), Issues, Pull Requests, deployKF website and Slack to find an approved method to configure these items, but have found nothing specifically addressing what I would consider to be a fundamental production grade configuration. The only configuration options I could find for these were in the Notebook server image profile configuration. (A default option in Kubeflow).

Looking at issue #117, I can see it's possible to set `valuesOverrides` on some of the deployKF dependencies, however in my testing this only allows you to override values defined by [deployKF itself](https://github.com/deployKF/deployKF/blob/main/generator/templates/manifests/deploykf-dependencies/cert-manager/values.yaml) for the chart, and not the inherent values of the original source chart.

>ℹ️ Note: It's possible that I have missed something, but certainly it's not clear in documentation on how to accomplish this.

I've found that I can edit the deployments afterwards and patch these configurations in via `kubectl` and ArgoCD doesn't complain that it's out of sync - however, manually patching deployments is obviously against the whole GitOps ethos.

### Implementation

My suggestion is that there should be the ability to configure the following on every deployKF deployment and managed dependency:

- tolerations
- affinity
- nodeSelector
- replicas

There could be a few implementation options for this:

1. Expose `tolerations`, `affinity`, `nodeSelector` and `replicaCount`/`replicas` configuration for each core and dependency deployment in the deployKF values files and adding the appropriate values to each manifest template.
2. Provide an alternate mechanism for patching/updating the deployments with these values via ArgoCD application/deployKF plugin that doesn't conflict with the sync state of the ArgoCD applications.
3. Provide documentation on creating a MutatingWebhookController to dynamically adjust these settings prior to ArgoCD creating the deployments in Kubernetes.

Then having some clear documentation on how to accomplish this configuration on the deployKF website would be appreciated.

### Are you willing & able to help?

- [ ] I am able to submit a PR!
- [x] I can help test the feature!

**Comment by berglh** [comment]
@thesuperzapper Showed us in Slack that we can set Helm chart values for the dependency deployments, but I'm still looking how to do this with the other deploykf auth/dashboard and Kubeflow components. For the dependency deployments the custom Helm chart values can be set by indenting the Helm values beneath a map with the chart name at the top level as per the values comments.

https://github.com/deployKF/deployKF/blob/5631e26721e4bbc2d3e494919330216ee4db28c6/generator/templates/manifests/deploykf-dependencies/kyverno/values.yaml#L47-L48

```yaml
  kyverno:
    enabled: true
    namespace: kyverno

    ## values overrides
    ##  - [WARNING] it is very easy to break something with this feature
    ##  - a map or string with values to override those generated by deployKF
    ##  - strings can include deployKF templates `{{< ... >}}`
    ##
    valuesOverrides: |
      kyverno:
        admissionController:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: karpenter.sh/nodepool
                  operator: In
                  values:
                  - "kubeflow"
          tolerations:
          - key: app.kubernetes.io/name
            operator: Equal
            value: kubeflow
            effect: NoSchedule
        backgroundController:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: karpenter.sh/nodepool
                  operator: In
                  values:
                  - "kubeflow"
          tolerations:
          - key: app.kubernetes.io/name
            operator: Equal
            value: kubeflow
            effect: NoSchedule
        cleanupController:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: karpenter.sh/nodepool
                  operator: In
                  values:
                  - "kubeflow"
          tolerations:
          - key: app.kubernetes.io/name
            operator: Equal
            value: kubeflow
            effect: NoSchedule
        reportsController:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: karpenter.sh/nodepool
                  operator: In
                  values:
                  - "kubeflow"
          tolerations:
          - key: app.kubernetes.io/name
            operator: Equal
            value: kubeflow
            effect: NoSchedule
```

**Comment by berglh** [comment]
I attempted to override the values for deploykf-auth via `valuesOverrides`, but it doesn't seem to do anything unlike for the dependencies based on Helm charts. It's not clear if replicas will work for these components either, but I wanted to check it out.

```yaml
deploykf_core:
  deploykf_auth:
    enabled: true
    namespace: deploykf-auth
    valuesOverrides: |
      dex:
        replicaCount: 3
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: karpenter.sh/nodepool
                  operator: In
                  values:
                  - "kubeflow"
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: dex
                  app.kubernetes.io/name: deploykf-auth
              topologyKey: kubernetes.io/hostname
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: dex
                  app.kubernetes.io/name: deploykf-auth
              topologyKey: topology.kubernetes.io/zone        
        tolerations:
          - key: app.kubernetes.io/name
            operator: Equal
            value: kubeflow
            effect: NoSchedule
      oauth2Proxy:
        replicaCount: 3
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: karpenter.sh/nodepool
                  operator: In
                  values:
                  - "kubeflow"
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: oauth2-proxy
                  app.kubernetes.io/name: deploykf-auth
              topologyKey: kubernetes.io/hostname
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: oauth2-proxy
                  app.kubernetes.io/name: deploykf-auth
              topologyKey: topology.kubernetes.io/zone        
        tolerations:
          - key: app.kubernetes.io/name
            operator: Equal
            value: kubeflow
            effect: NoSchedule
```

In the meantime, I can patch the deployments, but this causes ArgoCD to be out of sync as tolerations are not ignored in the diff spec.
