### ISSUE TITLE
Notebooks Redirect Client TLS Verification Failure

### ISSUE THREAD

**Issue by berglh** [deployKF/deployKF#253]
### Checks

- [x] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [x] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [x] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.5

### Kubernetes Distribution

EKS

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:47:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"30+", GitVersion:"v1.30.10-eks-bc803b4", GitCommit:"aaccd0763ddb0334edd559f7863815ea53ffb962", GitTreeState:"clean", BuildDate:"2025-02-17T20:41:03Z", GoVersion:"go1.22.12", Compiler:"gc", Platform:"linux/amd64"}
```

### Description

Running deployKF version 0.1.5 with self-managed Istio 1.22.8 with the Istio-CNI (ambient mode) plugin on AWS EKS 1.30. 

We use AWS ALB with TLS termination and forwarding to a NodePort to the TLS port of the deploykf-ingress-gateway. We manage a single istio-ingress-gateway deployment and don't let deployKF deploy it's istio-ingerss gateway, only the Gateway and Istio resources needed for it to function to the `istio-ingress` namespace.

Everything is working well apart from the notebook redirect. While the rest of our Kubernetes cluster is running in ambient mode, the sidecar operation of deployKF components is working as expected.

However, the connect button in the Jupyter web app results in the error:
```
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: TLS_error:|268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end:TLS_error_end
```

I've narrowed this down to the configuration of the DestinationRule for the notebook redirect:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  labels:
    app.kubernetes.io/instance: dkf-core--deploykf-istio-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: deploykf-istio-gateway
    argocd.argoproj.io/instance: dkf-core--deploykf-istio-gateway
    helm.sh/chart: deploykf-istio-gateway-1.0.0
  name: notebooks-redirect
  namespace: istio-ingress
spec:
  host: notebooks-redirect.my.domain.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE
  workloadSelector:
    matchLabels:
      app: istio-ingress-gateway
      istio: ingressgateway
```

What happens with this rule is that that the Istio ingress gateway itself acts as the client for the 302 redirect on the VirtualServer route redirect to the `https://notebooks-redirect.{kuebflow_domain}/notebook/profile/notebook_name/`. However, the Istio ingress gateway does not correctly trust the cert-manager self-signed bundle of the `deploykf-ingress-gateway`. This is fine in practice, but my DestinationRule generated by deployKF doesn't specify the `credentialName` value nor does it contain a structure for it to trust the TLS cert correctly even if it were specified.

I was able to circumvent this by adding the value [insecureSkipVerify](https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings-insecure_skip_verify) to the TLS block of the DestinationRule.

I have tried setting the [credentialName](https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings-credential_name) to the `deploykf-istio-gateway-cert` secret, however, the structure of the secret doesn't match what is expected as shown in the [credentialName](https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings-credential_name) documentation for the DestinationRule. Having a secret which matches the expected structure might be the better solution.

deploykf-istio-gateway-cert Secret
```json
"data":
  "ca.crt": "",
  "tls.crt": "",
  "tls.key": ""
```
Expected TLS client secret structure:
```json
"data":
  "cacert": "",
  "cert": "",
  "key": ""
```

Configuring your own certificates for deployKF would circumvent this with a trusted public CA; however, it might be useful to propagate a secret with the correct structure for the cert-manger self-signed bundle so that the TLS client of the Istio gateway can correctly validate the connection, or provide clear documentation and a values option on configuring `insecureSkipVerify` for the notebook redirect to avoid this redirect failure.

I didn't dig too deeply into what's deployed when you let deployKF manage its own Istio ingress gateway deployment. However, it took me quite a while to get past this issue through my own ignorance of how this is meant to be configured. Also, currently ArgoCD will overwrite this change if I'm not careful, I'm not sure how I can adjust the DestinationRule YAML from within deployKF values to either set `credentialName` or `insecureSkipVerify`. I may be missing something obvious also, but I couldn't find anything to this effect.

### Relevant Logs

```shell

```

### deployKF Values (Optional)

```yaml
deploykf_core:
  ## --------------------------------------
  ##        deploykf-istio-gateway
  ## --------------------------------------
  deploykf_istio_gateway:
    enabled: true
    namespace: istio-ingress

    ## values overrides
    ##  - [WARNING] it is very easy to break something with this feature
    ##  - a map or string with values to override those generated by deployKF
    ##  - strings can include deployKF templates `{{< ... >}}`
    ##
    valuesOverrides: {}

    ## extra manifests
    ##  - a list of strings containing extra Kubernetes resource manifests
    ##  - strings can include deployKF templates `{{< ... >}}` and Helm templates `{{ ... }}`
    ##
    extraManifests: []

    ## chart overrides
    ##
    charts:
      istioGateway:
        ## if false, you must create your own istio gateway ~deployment~ and ~service~
        ##  - you do NOT need to create resources like `networking.istio.io/Gateway`
        ##  - you must set the other values to match your deployment,
        ##    otherwise deployKF will be unable to use them
        enabled: false
        name: gateway
        ## NOTE: this version should be aligned with `deploykf_dependencies.istio.charts.istioDaemon.version`
        version: 1.17.8
        repository: https://istio-release.storage.googleapis.com/charts

    ## istio gateway configs
    ##
    gateway:

      ## the name of the Gateway resource, created by deployKF
      ##
      name: deploykf-ingress-gateway

      ## the hostname that the gateway will listen on
      ##  - subdomains of this hostname may also be used, depending on which apps are enabled
      ##
      hostname: kf.my.domain.com

      ## the ports that the gateway will listen on
      ##  - these are the "internal" ports which the gateway use, and can be different
      ##    to the user-facing ports which the service listens on, see `gatewayService.ports`
      ##  - you may need to set non-standard ports if you are using your own gateway service
      ##    (`charts.istioGateway.enabled` is false) and need to avoid conflicts with existing
      ##    services on the selected gateway deployment
      ##
      ports:
        http: 80
        https: 443

      ## gateway TLS configs
      ##
      tls:

        ## if the gateway will listen on HTTPS
        ##  - must ALWAYS be true (even if an outer proxy is doing its own TLS termination)
        ##
        enabled: true

        ## if browser clients use HTTPS when connecting to the gateway
        ##  - determines the protocol of links and cookies presented to client browsers,
        ##    should ~only~ be false if your end-users connect over HTTP, which is NOT recommended
        ##
        clientsUseHttps: true

        ## if the gateway will perform SNI matching on TLS connections
        ##  - typically needs to be ~false~ when using an outer proxy that does TLS termination (like AWS ALB),
        ##    as most cloud load-balancers don't forward the SNI for TLS connections that they terminate
        ##    https://istio.io/v1.19/docs/ops/common-problems/network-issues/#configuring-sni-routing-when-not-sending-sni
        ##
        matchSNI: false

        ## if the gateway will redirect all HTTP requests to HTTPS
        ##  - when false, the gateway will allow both HTTP and HTTPS connections
        ##  - [WARNING] you should ~only~ set this to false if you have an outer proxy doing TLS termination
        ##              that is ~unable~ to communicate with the gateway over HTTPS, and you don't care about
        ##              the security of the connections between your outer proxy and the gateway
        ##  - [WARNING] allowing HTTP connections will ~increase~ the load on your gateway pods,
        ##              this is because HTTP is implemented by proxying to HTTPS internally
        ##              (this strange behavior is required because of an Istio limitation and
        ##               the way we apply authentication to routes with EnvoyFilters)
        ##
        redirect: false

      ## the pod labels used by the gateway to find the ingress gateway deployment
      ##
      selectorLabels:
        app: istio-ingress-gateway
        istio: ingressgateway

      ## if "PROXY Protocol" is enabled on the gateway
      ## - requires Istio 1.17+ if enabled. will apply to all ports on the gateway
      ##   https://istio.io/v1.18/docs/ops/configuration/traffic-management/network-topologies/#proxy-protocol
      ##
      enableProxyProtocol: false

      ## the number of x-forwarded-for HTTP header hops to trust
      ##  - sets the number of hops from the right side of a `x-forwarded-for` HTTP header to trust
      ##    when determining the origin client's IP address
      ##
      xffNumTrustedHops: 2

      ## if the email passed in `X-Auth-Request-Email` by `oauth2-proxy` is cast to lowercase
      ##  - note, this will only affect the email passed to Kubeflow apps, other apps connected to
      ##    dex OIDC will still receive the original email, so it's usually best to standardize
      ##    the emails in your upstream identity system
      ##  - this may be helpful if your identity system returns emails with uppercase letters and you
      ##    want to standardize on lowercase emails for RoleBindings
      ##  - this value will also affect the profiles generated by `deploykf-profiles-generator`
      ##
      emailToLowercase: false

    ## istio gateway deployment configs
    ##
    gatewayDeployment:
      replicaCount: 1

      serviceAccount:
        name: istio-ingress-gateway
        annotations: {}

    #   autoscaling:
    #     enabled: true
    #     minReplicas: 1
    #     maxReplicas: 5
    #     targetCPUUtilizationPercentage: 80

    #   podAnnotations: {}

    ## istio gateway service configs
    ## This shouldn't be deployed
    gatewayService:
      name: deploykf-ingress-gateway
      annotations: {}
      type: NodePort
      loadBalancerIP: ""
      loadBalancerSourceRanges: []

      ## the ports that the gateway service listens on
      ##  - if unset, they default to their corresponding port under `gateway.ports`
      ##  - these are the "public" ports which clients are expected to connect to,
      ##    and can be different to the "internal" ports defined in `gateway.ports`
      ##  - when using your own gateway service (`charts.istioGateway.enabled` is false)
      ##    these values still affect the ports presented in user-facing HTTP links
      ##
      ports:
        http: 80
        https: 443
```
