### ISSUE TITLE
oauth2-proxy pod - Certificate Expiration

### ISSUE THREAD

**Issue by tom-pavz** [deployKF/deployKF#255]
### Checks

- [x] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [x] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [x] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.5

### Kubernetes Distribution

EKS

### Kubernetes Version

```shell
Client Version: v1.32.4
Kustomize Version: v5.5.0
Server Version: v1.32.3-eks-bcf3d70
```

### Description

After around ~60 days, logging into deployKF starts failing with a 500 status code, and I can see an associated error in the `oauth2-proxy` pod in `deploykf-auth` namespace like this:

```
[2025/04/30 16:50:42] [stored_session.go:193] Unable to refresh session: error refreshing tokens: unable to redeem refresh token: failed to get token: Post "https://<our domain>/dex/token": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2025-04-30T16:50:42Z is after 2025-04-30T16:36:47Z
```

This problem is always resolved if I just go in and manually restart the `oauth2-proxy` pod. I looked at the underlying `Certificate` and `Issuer` k8s resources and they look to be properly working and refreshing the cert as/before it expires, but for some reason it seems like the `oauth2-proxy` pod does not pick up the new cert until the pod is restarted.

Is there a better solution to this problem than having to manually go in and kick the pod every couple months? Thanks

### Relevant Logs

```shell
[2025/04/30 16:50:42] [stored_session.go:193] Unable to refresh session: error refreshing tokens: unable to redeem refresh token: failed to get token: Post "https://<our domain>/dex/token": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2025-04-30T16:50:42Z is after 2025-04-30T16:36:47Z
```

### deployKF Values (Optional)

```yaml
        ## a string containing the contents of a values file
        ##  - this parameter allows defining values without needing to create a file in the repo
        ##  - these values are merged with higher precedence than those defined in `values_files`
        ##
        - name: "values"
          string: |
            deploykf_dependencies:
              istio:
                enabled: false
                charts:
                  istioBase:
                    version: "1.20.3"
                  istioDaemon:
                    version: "1.20.3"
....
```
