### ISSUE TITLE
RBAC: access denied on minio artifacts in KFP

### ISSUE THREAD

**Issue by pbasov** [deployKF/deployKF#98]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT specific to the CLI. (If so, please open an issue on the [CLI repo](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.3

### Kubernetes Version

```shell
Client Version: v1.29.0
Server Version: v1.29.0
```

### Description

KFP artifacts stored in Minio are not available from KFP UI, throwing `RBAC: access denied` on trying to access `/pipeline/artifacts/minio/kubeflow-pipelines/artifacts/...`.

They are, however accessible with the same user from Minio console.
I'm using plain passwords to log in for now.

**Comment by thesuperzapper** [comment]
@pbasov can you please confirm if the step you are getting an RBAC issue was "cached" because it was first run in another namespace/profile?

deployKF will try and redirect you to the correct namespace, but if your logged in user does not have permission on the correct namespace, you will get an RBAC error.

**Comment by pbasov** [comment]
I'm a single user (apart from admin@example.com) in a single profile. I ran the pipeline from KF UI.
```
deploykf_auth:
  dex:
    staticPasswords:
    - email: "admin@example.com"
      password:
        value: ""
    - email: "mail@weystrom.net"
      password:
        value: ""
```
```
deploykf_profiles_generator:
  users:
    - id: weystrom
      email: "mail@weystrom.net"
  groups:
    - id: ml-team
      users:
        - weystrom
  profiles:
    - name: mirantis-ml-profile
      members:
        - group: ml-team
          access:
            role: edit
            notebooksAccess: true
```
